### ISSUE TITLE
Scrollbars and scrollable tables

### ISSUE THREAD

**Issue by birge** [zendeskgarden/react-components#101]
I am using the react scrollable table and noticed an alignment issues.

<img width="870" alt="screen shot 2018-08-08 at 4 38 11 pm" src="https://user-images.githubusercontent.com/1206124/43912671-c7697206-9bb7-11e8-8542-a02f6685e2b5.png">

The header doesn't line up with the body of the table.
There is a setting on mac os that effects this. 

<img width="447" alt="screen shot 2018-08-08 at 4 36 18 pm" src="https://user-images.githubusercontent.com/1206124/43912717-e719cdd0-9bb7-11e8-8651-fff973895abe.png">

When the setting is on `Automatic`, the scrollbars are overlaid and do not effect page layout, which is the case in the first screenshot. If they setting is on `Always` then the scrollbar is present and effects layout:

<img width="869" alt="screen shot 2018-08-08 at 4 37 59 pm" src="https://user-images.githubusercontent.com/1206124/43912770-117e938a-9bb8-11e8-93ad-534680c3f41e.png">

**Comment by austin94** [comment]
Looks like we should have been dynamically calculating the padding for the `<tbody>` since it became `display: block`

There are some examples of this in other packages with the `dom-helpers` library we are already using in some of our stuff. Will look for some examples.
