### ISSUE TITLE
Set value on input element using Dropdown component with Select

### ISSUE THREAD

**Issue by ghostropic** [zendeskgarden/react-components#1032]
## Expectations

I'd like the `input` element's `value` attribute populated with `selectedItem`.  I'm using `redux-forms`, and their validation function pulls from inputs within the form, but the one created from the `Dropdown` component isn't ever set. I tried setting it the way I am with the `Input` component but it isn't working. Maybe there is a way to pass the value down from `Dropdown` to `input`?

## Reality

When you inspect the `<input>` element created by the Dropdown component, the `value` attribute has no value. When I pass the props to the `Dropdown` component, they don't get attached to the created `input`.  From dev console, `value` is an empty string: 

```
<input id="downshift-0-input" aria-labelledby="downshift-0-label" aria-describedby="1val-field_1.3.7--hint" aria-autocomplete="list" autocomplete="off" readonly="" tabindex="-1" data-garden-id="forms.input" data-garden-version="8.32.2" class="sc-jSgupP jlvXuF sc-laRPJI ehtbPN" aria-invalid="false" value="">
```

## Steps to Reproduce

Here is my attempt to get it working with the `Dropdown` component: https://codesandbox.io/s/runtime-sun-s0557

Here i'm able to get it to work with the `Input` component: https://codesandbox.io/s/exciting-carson-48ef8

Also, when I tried to manually override the `input` value by finding the element and using `setAttribute` in vanilla js, and it was actually being removed when state changed.

**Comment by austingreendev** [comment]
There may be some ways of setting this with some of the [controlled Downshift props](https://github.com/downshift-js/downshift/). But, the input is an internal implementation detail handled by Downshift that could change over time.

Another approach that may help is to provide a custom input with `type="hidden"` that you can assign from the controlled Select value. This would ensure that the value is only set once a selection has been made. Something like:

```tsx
const Example = () => {
  const [selectedItem, setSelectedItem] = useState('item-1');

  return (
    <Form onSubmit={...}>
        <input name="my-select" value={selectedItem} type="hidden" />
        <Dropdown
          selectedItem={selectedItem}
          onSelect={newItem => setSelectedItem(newItem}>
          ...
        </Dropdown
    </Form>
  );
};
```

If that doesn't work for your needs the [Dropdown inputValue](https://github.com/downshift-js/downshift/#inputvalue) prop will allow you to control that value.

**Comment by ghostropic** [comment]
I might be able to get the hidden input to work but `redux-form` doesn't pull from hidden inputs for some reason, so I think I'd have to find a workaround there too. I tried setting the input value with `inputValue` but I think it only works with `autocomplete` which I'm not using, and doesn't seem to do anything here:

https://codesandbox.io/s/vigorous-water-0cp82?file=/src/Example.tsx:742-752
