### ISSUE TITLE
React > 17.0 Support

### ISSUE THREAD

**Issue by vitruvvius** [zendeskgarden/react-components#1038]
## Expectations

Zendesk support for next upgrade cycle of react

## Reality

peer dependency 16.8

## Steps to Reproduce

npm install 

### Fine Print

- Component: 
- Version: 
- Browsers: all

**Comment by austingreendev** [comment]
I believe we added support for React v17 in [this commit](https://github.com/zendeskgarden/react-components/commit/c840956c96afe9c769db41813c62dc241d4a79b1). Are you unable to upgrade at this time?

**Comment by jzempel** [comment]
Addressed by #1039.
