### ISSUE TITLE
Unable to export extended Components

### ISSUE THREAD

**Issue by pedropmedina** [zendeskgarden/react-components#1079]
## Expectations

Hoping to extend the styled components to reuse across app.

## Reality
```
export const StyledTable = styled(Table)`
  font-size: 13px;
`;
```
This causes the following error:
```
Exported variable 'StyledTable' has or is using name 'ITableProps' from external module "/Users/pedropmedina/Code/ricoma/integrations/integ-zendesk/web/node_modules/@zendeskgarden/react-tables/dist/typings/elements/Table" but cannot be named
```
Anyway to make this work, I need to extend the default Components and export in order to reuse somewhere in the app.

Thanks!

**Comment by jzempel** [comment]
You may find that [Targeting](https://garden.zendesk.com/components/theme-provider#targeting) via the `ThemeProvider` is more suitable for your use case.
