### ISSUE TITLE
Scrollable tables and RTL 

### ISSUE THREAD

**Issue by birge** [zendeskgarden/react-components#110]
Currently scrollable tables do not reverse in RTL.

<img width="997" alt="screen shot 2018-08-13 at 11 12 12 am" src="https://user-images.githubusercontent.com/1206124/44049763-d50abab6-9ee9-11e8-965e-e4c50c0546cb.png">

<img width="998" alt="screen shot 2018-08-13 at 11 12 23 am" src="https://user-images.githubusercontent.com/1206124/44049771-d83f1664-9ee9-11e8-9cd7-5dfe0a715545.png">

**Comment by austin94** [comment]
The legacy table was implemented with flexbox so the RTL was "free".

When I did the conversion to the new package style I went with `display: block` so this should probably be converted to flexbox.
