### ISSUE TITLE
Missing data-garden-id on Menu Item Icon

### ISSUE THREAD

**Issue by agrohs** [zendeskgarden/react-components#1128]
https://github.com/zendeskgarden/react-components/blob/d4fd7bc1cd62ce5107f8464b00fbec197d96d673/packages/dropdowns/src/elements/Menu/Items/Item.tsx#L95

Is it possible to add a `data-garden-id` to the Icon for a selected menu item so it can be targeted by css selector outside?? In previous garden versions where these were inserted via a pseduo selector they could easily be found, but in the new setup without a `data-garden-id` on the `StyledItemIcon` its quite a pain.

**Comment by hzhu** [comment]
Hey @agrohs, thanks for bringing this to our attention. In the meantime, would you be able to style the icon using a scoped styled component? Here's an example: https://codesandbox.io/s/gifted-rhodes-0fc8w.
