### ISSUE TITLE
AutoComplete Popper Promise Rejection Issues

### ISSUE THREAD

**Issue by louisscruz** [zendeskgarden/react-components#134]
## Expectations

There are issues with `popper.js` and `jsdom`, particularly surrounding the usage of `document.createRange`.

The fix for this is usually to mock `popper.js` and/or create a stub for `document.createRange`.

We use a mock for `popper.js` in other parts of our codebase, and that seems to fix the issue.

We started seeing this problem again with `react-autocomplete`. I attempted to fix it the usual way.

## Reality

I can't seem to get the errors to go away:

```
(node:75263) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: document.createRange is not a function
(node:75263) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: document.createRange is not a function
```

When I attempt to fix it with a `document.createRange` stub, I then get:

```
Warning: `NaN` is an invalid value for the `top` css style property.
```

I've tried all of the solutions here with no luck:

https://github.com/FezVrasta/popper.js/issues/478

Note: I've been clearing the cache, etc. to ensure that wasn't the issue I'm experiencing.

Does `react-autocomplete` bring in a different version of Popper or something? I'm not sure how to proceed with removing these errors.

## Steps to Reproduce

Use `react-autocomplete` and run Jest tests.

###### Fine Print

* Component: autocomplete
* Browsers: n/a (Node/Jest)

**Comment by ryanseddon** [comment]
Hey @louisscruz are you able to run `npm ls` or `yarn list` and `grep` the results to see if you have duplicate versions of popper in dependency tree.

**Comment by jzempel** [comment]
@louisscruz closing as the conversation seems to have stalled here. Please re-open if you have feedback for @ryanseddon re: duplicate dependencies.
