### ISSUE TITLE
Accordions | Aria-hidden elements contain focusable elements

### ISSUE THREAD

**Issue by anayadesign** [zendeskgarden/react-components#1383]
## Expectations
- Accordions pass accessibility tests
- Nested components in _collapsed_ Accordion.Panels cannot be :focused

## Reality
When an Accordion.Panel contains a keyboard-focusable component (Button or Anchor link for example), those elements are still focusable when the Panel is _collapsed_ and has the `aria-hidden='true'` attribute.
- https://dequeuniversity.com/rules/axe/4.1/aria-hidden-focus

## Steps to Reproduce

1. Visit the code sandbox example https://codesandbox.io/s/blissful-frost-n21kpc
2. Keyboard :focus your way through the Accordion
3. The `#tomato` Anchor should be available in the keyboard-tab flow, between 'what are the basics of gardening?' and 'What are the best tools?' `Accordion.Header`s

### Fine Print

- Component: [Accordion](https://github.com/zendeskgarden/react-components/tree/main/packages/accordions)
- Version: 8.53.2
- Browsers: all

**Comment by jzempel** [comment]
Thanks, @anayadesign. We'll need to sort out taking the panel out of the tab order (i.e. applying the `hidden` attribute) in conjunction with the animation timing for accordion show/hide. Stay tuned.

**Comment by abbelco** [comment]
@jzempel This PR has been open for 11 days - should we add this to our backlog or is there a status on this? Wondering if we should close this out so it doesn't get stale and we can reopen when the work is prioritized. LMK!

**Comment by jzempel** [comment]
@abbelco given competing priorities, Garden may be delayed on getting to this. In the mean time, I would suggest using a library like [tabbable](https://www.npmjs.com/package/tabbable) to identify and set your focusable content to `tabIndex={-1}` when an accordion panel is collapsed.

Ultimately, Garden can't take this brute-force approach with the TBD solution, but it might work when you know more about the shape of your accordion content.
