### ISSUE TITLE
Dropdown Menu throwing properties undefined error reading rtl

### ISSUE THREAD

**Issue by AzySir** [zendeskgarden/react-components#1416]
## Expectations

Expected to have a working dropdown menu but this does not seem to be the case

## Reality

Error for RTL that looks like (below screenshot) 

<img width="521" alt="Screen Shot 2022-10-06 at 1 18 27 am" src="https://user-images.githubusercontent.com/37623164/194186464-289c97e8-be51-4c1d-9324-7485a1196a8f.png">

## Steps to Reproduce

1. `npm install @zendeskgarden/react-dropdowns @zendeskgarden/react-theming`
2. Code below

```
import "./styles.css";
import {
  Item,
  Menu,
  Label,
  Field,
  Dropdown,
  Autocomplete
} from "@zendeskgarden/react-dropdowns";

export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <Dropdown>
        <Menu></Menu>
      </Dropdown>
    </div>
  );
}

```

Code Sandbox: https://codesandbox.io/s/magical-dubinsky-snio2k?file=/src/App.js

**Comment by jzempel** [comment]
Please surround your code with a `<ThemeProvider>` as described here: https://github.com/zendeskgarden/react-components#usage

**Comment by AzySir** [comment]
@jzempel 

Thanks for your reply - I've done that and it's not showing anything at all it's just null

https://codesandbox.io/s/magical-dubinsky-snio2k?file=/src/App.js

**Comment by AzySir** [comment]
Also now hit an error with the Datepicker. ThemeProvider related.

**Comment by AzySir** [comment]
3 issues here 

1) ThemeProvider not added as  @jzempel (Probably needs a better error message if possible?) 

2) React 18 was not setup so I upgraded 

3) <Autocomplete> tag was missing - now this description on the documentation + the name of the actual Component is very misleading considering it seems to be the main handler for the state of the dropdown. What is the relevance of Autocomplete I'm not sure - I presumed that it was if you type into the dropdown it will return a value via this Component.  

Steps to Fix:

1) Added ThemeProvider
2) Update to `npm install react@18 react-dom@18` then fixed the index.js 
3) Re-added <Autocomplete> after many sandbox tests learning this was missing
