### ISSUE TITLE
Menu inline search example jumps on open

### ISSUE THREAD

**Issue by sunesimonsen** [zendeskgarden/react-components#142]
## Expectations

When opening this opening the menu in the inline search example in this section https://garden.zendesk.com/react-components/menus/#menucontainer the page scrolls in different ways depending on the browser. I expect the main page to not scroll at all.

## Reality

Chrome running the styleguide locally:

![auto_scroll](https://user-images.githubusercontent.com/90802/44977769-34f99980-af69-11e8-892b-835180192318.gif)

Firefox running the https://garden.zendesk.com/react-components/menus/#menucontainer example:

![scroll to top](https://user-images.githubusercontent.com/90802/44977817-5bb7d000-af69-11e8-8fe1-6ebcec63cce4.gif)

When running https://garden.zendesk.com/react-components/menus/#menucontainer in Chrome I get a quick flicker that I wasn't able to capture with a gif.

## Steps to Reproduce

  1. Open the inline search example

###### Fine Print

* Component: menus
* Browsers: all

**Comment by austin94** [comment]
Looks like this is an issue with the `.focus()` timing and the animation placement of the `MenuView`.

This would be an issue with the example only and not in the `MenuContainer` so should be a quick fix.  Might be able to be a into #141

**Comment by austin94** [comment]
This pattern is no longer used and is replaced in #315 

The `Autocomplete` example in https://garden.zendesk.com/react-components/dropdowns/ is the immediate replacement. Thanks for opening this!

**Comment by sunesimonsen** [comment]
👍
