### ISSUE TITLE
Multiselect: Add-new item causes `onSelect` handler to fire twice

### ISSUE THREAD

**Issue by Anifacted** [zendeskgarden/react-components#1519]
In the Multiselect component, when having the option of adding a new item to the list (via the AddItem component), hitting ENTER to confirm the action causes the `onSelect` handler to be called twice.
Note: It does not happen when simply clicking the AddItem. In this case, the handler is fired once as expected.

## Expectations

I expect that hitting ENTER with the AddItem highlighted invokes the `onSelect` handler once.

<img width="405" alt="Screenshot 2023-02-20 at 14 03 48" src="https://user-images.githubusercontent.com/6997051/220116659-71ff201c-c016-4cf4-9c6a-a156be3c2fd0.png">

## Reality

Hitting ENTER with the AddItem highlighted invokes the `onSelect` handler twice.

<img width="414" alt="Screenshot 2023-02-20 at 14 03 28" src="https://user-images.githubusercontent.com/6997051/220116692-8b4adef3-568b-4bee-bd81-a351e16f12ee.png">

## Steps to Reproduce

1. Go to codesandbox: https://codesandbox.io/s/intelligent-booth-veebni?file=/src/Example.tsx
1. Open the console
1. Click the Multiselect component, enter a search and hit ENTER over the "Add new"-item
1. Observe how the items are logged twice (i.e. the onSelect handler was invoked twice).

### Fine Print

- Component: Multiselect
- Version: v8.48.0 (and forward)
- Browsers: all

### Notes

I observed this bug to have been introduced in v8.48.0 of `react-dropdowns`, since v8.47.0 does not have the issue.
Here's a comparison between the two: https://github.com/zendeskgarden/react-components/compare/v8.47.0...v8.48.0

I am led to suspect that this commit could be responsible given its description: https://github.com/zendeskgarden/react-components/commit/1664050191e7d981af7b0647fac9180943327093

**Comment by Francois-Esquire** [comment]
Hey @Anifacted thank you for the comprehensive report! This is a known issue we have been tracking and will hopefully get to it in the coming future. Thanks for being patient with us.

**Comment by jzempel** [comment]
@Anifacted please use the new `Combobox` where this is fixed (along with numerous a11y issues). Please see the following references for details:
- https://www.npmjs.com/package/@zendeskgarden/react-dropdowns.next
- https://zendeskgarden.github.io/react-components/?path=/story/packages-dropdowns-next-combobox--uncontrolled
- https://codesandbox.io/s/combobox-demo-vhhlgh?file=/src/ComboboxNext.tsx
