### ISSUE TITLE
Icon Button component does not get labelled by Tooltip programmatically

### ISSUE THREAD

**Issue by jgorfine-zendesk** [zendeskgarden/react-components#1536]
## Expectations

Icon Button must have an [accessible name](https://www.w3.org/TR/wai-aria-1.1/#dfn-accessible-name). This is different from an [accessible description](https://www.w3.org/TR/wai-aria-1.1/#dfn-accessible-description), which defined in the latest WAI-ARIA spec as:
> ...additional information, related to an interface element, that complements the accessible name.

## Reality

axe-core flags the Icon Button component with a critical [button-name issue](https://dequeuniversity.com/rules/axe/4.7/button-name?application=RuleDescription).

![Zendesk A11y Tools flags the out-of-the-box Icon Button component for having a button-name issue](https://user-images.githubusercontent.com/93289772/233133963-d4ba419b-0151-49a7-990c-4441f0285b68.png)

> Selector: `button[aria-describedby="1val-tooltip_1.0.4"]`
>
> Rule ID: button-name
> 
> Issue: Buttons must have discernible text
> 
> Description: Ensures buttons have discernible text
> 
> Recommendation: Fix any of the following: Element does not have inner text that is visible to screen readers aria-label attribute does not exist or is empty aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty Element has no title attribute Element's default semantics were not overridden with role="none" or role="presentation"
> 
> Impact: critical
> 
> Tags: cat.name-role-value,wcag2a,wcag412,section508,section508.22.a,ACT
> 
> HTML: `<button tabindex="0" aria-describedby="1val-tooltip_1.0.4" data-garden-container-id="containers.tooltip" data-garden-container-version="1.0.4" data-garden-id="buttons.icon_button" data-garden-version="8.64.0" type="button" class="StyledButton-sc-qe3ace-0 StyledIconButton-sc-1t0ughp-0 eAxVVY hMXJNg">`

and screen readers, like VoiceOver, don't always know what the name of the Icon Button is:

![Screenshot of VoiceOver Form Controls menu listing one unlabelled button and two labelled buttons](https://user-images.githubusercontent.com/93289772/233130460-c368cf87-deb9-4c03-925b-b43b74f5ab5e.png)

### Icon Button, out of the box

![Computed name for the out-of-the-box Icon Button is blank](https://user-images.githubusercontent.com/93289772/233130226-16376c75-4642-4f21-9873-209d411e0aa0.png)

### Icon Button, with `aria-label` declared again

![Computed name and description for the Icon Button is "Leaf," when aria-label is provided](https://user-images.githubusercontent.com/93289772/233130275-adebef29-03d5-424b-81af-934b53421157.png)

### Icon Button, with `aria-label` declared again & `aria-describedby` unset

![Computed name for the Icon Button is "Leaf," when aria-describedby is undefined](https://user-images.githubusercontent.com/93289772/233130327-3c7f6592-d002-4360-b5bc-f32e498f81ae.png)

## Demo

[CodeSandbox](https://codesandbox.io/s/icon-button-labelling-demo-8097m1?file=/src/Example.tsx)

## Fine Print

- Component: [Icon Button](https://garden.zendesk.com/components/icon-button)
- Version: 8.64.0 (latest at this time)
- Browsers: all

**Comment by jgorfine-zendesk** [comment]
That example happens to demonstrate the risk in asking consumers to repeat text: they don't match. In the example, the Tooltip reads `Leaf` while the ARIA label reads `leaf`:

![The code snippet used in the Default Icon Button example on the Garden website](https://user-images.githubusercontent.com/93289772/233166453-32591a70-f525-498f-8f62-9cb741d20ee4.png)

While it may not seem like a huge deal in this particular example, this mismatch could be confusing for screen reader users who're seeing one label and hearing another,  depending on what values get passed in. After all, not all screen reader users have low/no vision.

There's an opportunity here to make the component more robust by having the button be labelled by the Tooltip via `aria-labelledby`, under the hood.

**Comment by geotrev** [comment]
Worth calling out: as consumers build experiences with shadow roots, using `aria-labelledby` becomes [broken/inaccessible](https://nolanlawson.com/2022/11/28/shadow-dom-and-accessibility-the-trouble-with-aria/).

Until the [current AOM proposal](https://wicg.github.io/aom/caniuse.html) moves into phase 2 and browsers implement a node ref alternative to id ref attributes, it's unfortunately a non-starter. :(

**Comment by jzempel** [comment]
Closing for now as there's no plan to address the issue at this time. We'll revisit if it becomes a more prominent audit topic.
