### ISSUE TITLE
Avatar: extraneous `console.warn` about missing `statusLabel`

### ISSUE THREAD

**Issue by tgohn** [zendeskgarden/react-components#1537]
## Expectations
No `console.warn` about missing `statusLabel` is logged when using `<Avatar />` component without `status` or `badge` props.

Consumer of `<Avatar />` should not need to add `statusLabel` props if they do not render avatar's badge or status icons.

## Reality
When using a vanilla  `<Avatar />` component without `status` or `badge` props, there is a extraneous `console.warn`
```console
Warning: you did not provide a customized/translated `statusLabel` text value for <Avatar>. Zendesk Garden is rendering <Avatar statusLabel="status"> by default. 
```
<details>

<img width="2557" alt="Screenshot 2023-04-21 at 11 09 38 AM" src="https://user-images.githubusercontent.com/6629569/233531848-67286ed2-345c-4e1a-8fc5-b0962c03d7b5.png">

</details>

## Steps to Reproduce

1. Visit this [codesandbox](https://codesandbox.io/s/effwo2?module=src/Example.tsx&file=/src/Example.tsx), which is the first example of `<Avatar/>` in [the guide](https://garden.zendesk.com/components/avatar#shape)
1. `console.warn` was printed out, similar to screenshot above

### Fine Print

- Component: `Avatar`
- Version: `v8.64.0`
- Browsers: all

**Comment by tgohn** [comment]
There is a relevant [discussion here](https://github.com/zendeskgarden/react-components/pull/1403#discussion_r960619077) prior.

**Comment by geotrev** [comment]
Thanks for the heads up @tgohn - this should be relatively straightforward. Will have a PR up shortly.
