### ISSUE TITLE
Radio Buttons are not Functional for multiple inputs

### ISSUE THREAD

**Issue by couturecraigj** [zendeskgarden/react-components#1557]
## Expectations
`<Radio/>` should allow multiple combinations of radio button fields... example one question
Do you like cats or dogs? choose cats or dogs.
Do you like vanilla or chocolate? choose vanilla or chocolate
Both cats and Chocolate should be able to be selected at the same time.

## Reality
has some unexpected functionality when using it in multiple locations.
When I put `<Field><Radio><Label /></Radio></Field>` as given in the examples... it will only allow you to select one of all four options.  So I cannot like Cats and Chocolate or Dogs and Vanilla.  This seems like standard functionality that should be included in a radio option.

## Steps to Reproduce

1. Put a Radio somewhere in your app and then a radio somewhere else in your app on the same page... it will not be your friend

### Fine Print

- Component: Radio 
- Version: 8.62 
- Browsers: all

**Comment by jzempel** [comment]
Hi @couturecraigj. Garden's `<Radio>` renders a native `<input type="radio">` which inherently only allows one in a group to be selected at the same time. (See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio). I think you're looking for [Checkbox](https://garden.zendesk.com/components/checkbox).

**Comment by couturecraigj** [comment]
Actually, no.  I want somebody to select one of either cats or dogs and one of either chocoloate or vanilla... that is not the same as a checkbox.

**Comment by jzempel** [comment]
Could you provide a [codesandbox](https://codesandbox.io/) that demonstrates the problem you're seeing?

**Comment by couturecraigj** [comment]
nvm... I just was not passing the name as a property on the input.
