### ISSUE TITLE
Warning from React for using defaultProps on ToastProvider

### ISSUE THREAD

**Issue by jvictorvilela** [zendeskgarden/react-components#1607]
I'm having this annoying warning when using ToastProvider.
It looks like React will remove defaultProps in the future.

<img width="457" alt="image" src="https://github.com/zendeskgarden/react-components/assets/22122135/02623a3d-fc06-4740-bf43-47a447c427e3">

**Comment by jzempel** [comment]
Garden will address this across the entire component set in a future release.

**Comment by jvictorvilela** [comment]
Thanks!

**Comment by lfx-br** [comment]
@jzempel 
Hi, I appreciate your time. I was wondering if this issue has been addressed in Garden yet. Thank you!
