### ISSUE TITLE
Problem with inputs focused after opening and closing modal

### ISSUE THREAD

**Issue by jvictorvilela** [zendeskgarden/react-components#1608]
## Expectations

After opening and closing a modal, navigation between inputs is expected to occur normally.

## Reality

After opening and closing any modal, when navigating between inputs (using the tab key), the inputs are permanently focused.

<img width="558" alt="image" src="https://github.com/zendeskgarden/react-components/assets/22122135/e437bc51-7f45-4cba-a51a-33495213d115">

## Steps to Reproduce

1. Open a modal (Modal component) and close it 
2. Click on an input (Input component) and navigate between the inputs using the tab key

Example: https://codesandbox.io/s/garder-bug-jrxygm

### Fine Print

- Components: Input and Modal
- Version: 8.69.7
- Browsers: all

**Comment by geotrev** [comment]
Hi @jvictorvilela. I noticed a few things about your reproduction that may be contributing to the issue:

- Garden components are expected to run within a [`ThemeProvider` instance](https://garden.zendesk.com/components/theme-provider) from the app root
- Right now, Garden isn't fully compatible with `styled-components@6` (v5 should be fine)
- We're experiencing mixed results with `StrictMode` right now, I would be curious if removing that changes any behavior.; that said, none of the components in your reproduction showed issues with `StrictMode` in our testing, so this is less likely/
- Garden is also in the process of upgrading to `react@18`, so v17 is the best bet right now (this doesn't apply if you're not using `StrictMode`)

**Comment by jvictorvilela** [comment]
Great, the problem really occurred because I didn't involve my "application" with the ThemeProvider. Thank you for your help.

Obs.: The mandatory ThemeProvider should be clearer in the documentation, since not using the component causes these strange behaviors.
