### ISSUE TITLE
Props being applied to DOM elements.

### ISSUE THREAD

**Issue by ffind** [zendeskgarden/react-components#1617]
## Expectations

  I showed up, expecting to have my mind blown.

## Reality
 Using  ToastProvider for [Notification](https://garden.zendesk.com/components/notifications) component, and there is an issue that toast provider props for some reason being applied to DOM elements.

<img width="544" alt="Screenshot 2023-08-31 at 16 50 07" src="https://github.com/zendeskgarden/react-components/assets/11630575/4a7a01bb-0917-46d1-8eda-52f80a60d323">

<img width="502" alt="Screenshot 2023-08-31 at 16 47 55" src="https://github.com/zendeskgarden/react-components/assets/11630575/962a0ed4-bcd6-4a3f-aed3-cc8a27e30c52">

## Steps to Reproduce

1. Install @zendeskgarden/react-notifications
2. 
```jsx
 <ToastProvider placementProps={placementProps} zIndex={1} limit={3}>{children}</ToastProvider>
```

### Fine Print

- Component:  **@zendeskgarden/react-notifications**
- Version: **8.69.9**
- Browsers: **all**
- Bundler: **vite 4.3.9**

**Comment by jzempel** [comment]
Thanks @ffind. We're aware of the issue. The fix will require a `styled-components` peer dependency bump. So we're holding off until v9.

**Comment by ffind** [comment]
Keeping high! Thank you @jzempel

**Comment by bkw** [comment]
@ffind thanks for working on this. Is there an ETA for v9?
