### ISSUE TITLE
Default MediaInput styling on click spreads over all MediaInputs on the page

### ISSUE THREAD

**Issue by nyckyta** [zendeskgarden/react-components#1674]
## Expectations

First of all, I expect that when I click on MediaInput only that component I clicked on should be highlighted and styled as focused.
For example, this is the way it works with regular inputs.

https://github.com/zendeskgarden/react-components/assets/43041066/7a8e3c59-d40e-46a0-9911-0446c16f407f

Second, you can see that in the end of the video I clicked on the empty area and focus was removed from the focused component.

## Reality

When I use completely the same code with MediaInput, it focuses both inputs and it is impossible to remove focus clicking on the empty are.

https://github.com/zendeskgarden/react-components/assets/43041066/a1409a24-4f66-4288-affb-b3db65585507

## Steps to Reproduce
Just render few components and click on them by left mouse button in the way it is depicted on video. No 'custom' configuration is needed.

There is a [sandbox example
](https://codesandbox.io/p/sandbox/proud-flower-l689vg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqi4s0zx00062e66931f1bxw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqi4s0zx00022e66zxp3gj9v%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqi4s0zx00032e66e00wwbis%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqi4s0zx00052e66dcydfurm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqi4s0zx00022e66zxp3gj9v%2522%253A%257B%2522id%2522%253A%2522clqi4s0zx00022e66zxp3gj9v%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqi4s0zx00052e66dcydfurm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqi4s0zx00042e66yi28ba1p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqi4s0zx00052e66dcydfurm%2522%252C%2522activeTabId%2522%253A%2522clqi4s0zx00042e66yi28ba1p%2522%257D%252C%2522clqi4s0zx00032e66e00wwbis%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqi4s0zx00032e66e00wwbis%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
### Fine Print

- Component: @zendesk-garden/react-forms/MediaInput
- Version: looks like it is latest
- Browsers: tried in a firefox and chrome

**Comment by nyckyta** [comment]
Btw, the similar issue appears with Multiselects (when you select Multiselect it focuses all Multiselects as well as all MediaInputs on the page). However, I see that it is deprecated and new Comboboxes do not have this issue. 

I hope this will help you to figure out the issue.

**Comment by jzempel** [comment]
@nyckyta I'm running your example here and focus is working as expected: https://codesandbox.io/p/sandbox/multi-inputs-2xvnc8

**Comment by nyckyta** [comment]
Hi @jzempel . Right, it has been fixed on our side as well since few last builds. I suppose it was related to some dependecies, but unfortunately we did not track lock file properly.

So, I believe this ticket can be closed unless you want to have investigation anyway.

**Comment by jzempel** [comment]
Thanks @nyckyta. Please re-open if you experience unexpected results.
