### ISSUE TITLE
Give styled buttons access to keyboardFocused state

### ISSUE THREAD

**Issue by aravindet** [zendeskgarden/react-components#174]
## Expectations

The Garden Button displays a focus shadow when it receives focus as a result of a keyboard interaction, but not when it receives focus as a result of a mouse interaction.

This is accomplished using the `KeyboardFocusContainer`, which provides a `keyboardFocused` flag to the render prop.

It is often necessary to add styling to the Garden button, for example to change its background color. In this scenario, it is also necessary to change the color of the focus shadow. One could do this with:

```js
const StyledButton = styled(Button)`
  background-color: red;
  :focus {
    box-shadow: 0 0 0 3px red;
  }
`;
```

but `:focus` does not have the same behaviour the actual button, which adds the `is-focused` class on `keyboardFocused || props.focused`.

There should be a way for styled buttons to override styling for specific button states, without having to reimplement the logic of how it gets into that state.

## Reality

There isn't.

## Suggestion

In Button:

```js
class Button {
  ...
  static classNames = ButtonStyles;
}
```

In StyledButton:

```js
const StyledButton = styled(Button)`
  background-color: red;
  &.${Button.classNames['is-focused']} {
     box-shadow: 0 0 0 3px red;
  }
`;
```

As CSS Components is also an open source project, class names like 'is-focused' are already a documented part of the Garden public API.

This approach is generic enough to handle all such use cases (other states and other components).

###### Fine Print

* Component: Buttons, but maybe others?
* Browsers: all

**Comment by ryanseddon** [comment]
Within your component you can access props, so to accomplish changing the focus style when it's prop based and not css based you can do the following:

```js
const focusRing = 'box-shadow: 0 0 0 3px red;';
const StyledButton = styled(Button)`
  background-color: red;
  :focus {
    ${focusRing}
  }
  ${(props) => props.focused && focusRing;
`;
```

**Comment by aravindet** [comment]
`keyboardFocused` is not a prop. The component structure is:

```
<StyledButton>
  <Button>
    <KeyboardFocusContainer>
      <button></button>
    </KeyboardFocusContainer>
  </Button>
</StyledButton>
```

`keyboardFocused` is an argument that the `KeyboardFocusContainer` passes to its render prop (an anonymous function that returns a `<button>`. I can't intercept this in the StyledButton.

**Comment by aravindet** [comment]
Also, this is part a more generic problem.

Garden often has intricate rules about what combinations of props and user interactions cause a component to enter and leave certain states. Here we're talking about button focus, but this also applies to other states like active, hover, menu open/closed etc.

It is extremely useful for consumers to be able to override the component's styling in a particular state without having to know and reimplement these rules. In other words I would like to say, "When the component is in state X, apply this style" without knowing how Garden decides whether the component is in state X or not.
