### ISSUE TITLE
react-theming has issue in StyledBaseIcon import statement

### ISSUE THREAD

**Issue by mobasherfasihi** [zendeskgarden/react-components#1950]
## Expectations
I'm using React-garden, when I run `npm run dev`, the following error happens.

## Reality

react-theming has the following issue 
```
✘ [ERROR] No matching export in "node_modules/@zendeskgarden/react-theming/dist/esm/index.js" for import "StyledBaseIcon"

    node_modules/@zendeskgarden/react-chrome/dist/esm/styled/header/StyledHeaderItemIcon.js:8:9:
      8 │ import { StyledBaseIcon, retrieveComponentStyles } from '@zendeskgarden/react-theming';
        ╵          ~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@zendeskgarden/react-theming/dist/esm/index.js" for import "StyledBaseIcon"

    node_modules/@zendeskgarden/react-chrome/dist/esm/styled/nav/StyledNavItemIcon.js:8:9:
      8 │ import { StyledBaseIcon, retrieveComponentStyles } from '@zendeskgarden/react-theming';
        ╵          ~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@zendeskgarden/react-theming/dist/esm/index.js" for import "StyledBaseIcon"

    node_modules/@zendeskgarden/react-chrome/node_modules/@zendeskgarden/react-buttons/dist/esm/styled/StyledIcon.js:8:9:
      8 │ import { StyledBaseIcon, retrieveComponentStyles } from '@zendeskgarden/react-theming';

```

**Comment by jzempel** [comment]
@mobasherfasihi please provide a codesandbox that reproduces the error. You can start by using the "Open in CodeSandbox" option on [this example](https://garden.zendesk.com/components/chrome#default). From there, we should be better able to assist you. A couple of things to keep in mind:
- the required dependencies mentioned in the [configuration](https://garden.zendesk.com/components/chrome#configuration)
- [ADR](https://github.com/zendeskgarden/react-components/blob/main/docs/adrs/001-theming-peer-dependency.md) that requires theming to be up-to-date

**Comment by jzempel** [comment]
Closed due to inactivity
