### ISSUE TITLE
Export ES6 modules

### ISSUE THREAD

**Issue by nullobject** [zendeskgarden/react-components#198]
This is a nice project 👏 

It would be ace if you could include the ES6 modules in the exported assets and reference them in the `package.json` file.

That would make it possible to use the ES6 module directly in other projects, rather than relying on only the commonjs version.

**Comment by ryanseddon** [comment]
Thanks @nullobject ❤️ that is definitely something we have been thinking about. 

We do currently have cjs and umd builds we ship in the package might make sense to ship an `esm` version too.

**Comment by nullobject** [comment]
Hi @ryanseddon, that would be awesome.

I'm looking to build a UI component library at The Conversation, which re-exports some of the zendesk garden components and makes some theme tweaks, etc. That way the apps that consume it wouldn't be too tightly coupled to a particular version of the zendesk components.

I was trying to do this using rollup, but couldn't get it working with anything other than a component package which exports a `esm` library.
