### ISSUE TITLE
Add error for `withTheme` usage without a parent `ThemeProvider`

### ISSUE THREAD

**Issue by austin94** [zendeskgarden/react-components#20]
## Expectations

Whenever one of our internal components (or external usages) use the `withTheme` HOC to determine the current RTL locale without a parent `ThemeProvider`, it should throw an error.  When using the `styled-components` withTheme HOC without the parent ThemeProvider it will fail in a production build only.

We should make it obvious that something is going to break by throwing an error and stoping rendering rather than a `console.warn()`

## Reality

When using a `withTheme` HOC without a `ThemeProvider` the user sees a `console.warn()`. For consumers this isn't immediately identifiable as something that will "break the world".

## Steps to Reproduce

1. Use Garden container or element
1. Do not wrap it in a `ThemeProvider`
1. Do a production build
1. Watch the world 🔥 

###### Fine Print

* Component: all packages using `@zendeskgarden/react-theming` (everything)
* Browsers: all

## Solution

I suggest that we include a context check between our `ThemeProvider` and `withTheme` components. This check will throw an error within `withTheme` if there is no parent ThemeProvider.

@eddiesholl what are your thoughts on this?

**Comment by eddiesholl** [comment]
I feel like its bad enough that `styled-components` should address it as well, there's an issue for it https://github.com/styled-components/styled-components/issues/1709. I'm thinking about a submitting a PR over there.

In the mean time, adding some protection in garden definitely seems like a useful thing. Given the situation, I feel like an error in dev mode is reasonable.

**Comment by aravindet** [comment]
A warning already exists on Styled Components now.

**Comment by jzempel** [comment]
Closing as the conversation seems to have stalled on this one. Please re-open if it needs further consideration.
