### ISSUE TITLE
Questions regarding AutoComplete component

### ISSUE THREAD

**Issue by Fabiantjoeaon** [zendeskgarden/react-components#214]
Hi there,

Thank you for publishing your UI system that makes use of `styled-components`. I tried different ones, but they don't look as nice as this one.

I do have some problems with the AutoComplete example however, the examples online are a bit awkward.. Which is a pity because they look very intuitive. I created this issue to hope to get some light shed on my questions, and to make some remarks. If this is not the place to do so, my apologies. The following is mostly regarding the examples, because the API reference overall is pretty clear.

- Is there a specific reason you import from src? (`[zendesk-package]/src`)
- I believe the first example is broken, it assume most of the code belongs in the `render` method? Also some imports are missing I believe, like `AutocompleteContainer`.
- What exactly is the `State` component? I don't see it imported.
- I saw `AutoComplete` is inspired by the work of `DownShift` (on twitter somewhere), what is the benefit of creating a custom version when you still have to implement most of it yourself? Or does it actually use Downshift under the hood?

**Comment by ryanseddon** [comment]
👋 Hey @Fabiantjoeaon,

Thanks for the questions. I'll try and answer them inline below.

> Is there a specific reason you import from src? (`[zendesk-package]/src`)

This is due to an issue with lerna and our CI build it's not a representation of how you might do it if you were to install via npm. See #115.

We have plans to improve on our docs and examples.

> I believe the first example is broken, it assume most of the code belongs in the `render` method? 

The `AutocompleteContainer` is a [render prop](https://reactjs.org/docs/render-props.html) based component so you supply a function as `children` or use the `render` prop e.g.

```jsx
<AutocompleteContainer>
	{/* you supply a function here that the above cotnainer passes in some prop getters */}
	{function({ getMenuProps, getItemProps, placement, focusedKey }) {
		// Use prop getters here to spread onto your dom elements
	}}
</AutocompleteContainer>
```

> Also some imports are missing I believe, like `AutocompleteContainer`

`AutocompleteContainer` is automatically available via react-styleguidist live examples so we don't need to import it.

> What exactly is the State component? I don't see it imported.

It's a convenience component to supply state and the setState method to the examples you can see the [source here](https://github.com/zendeskgarden/react-components/blob/master/utils/styleguide/State/index.js).

> I saw AutoComplete is inspired by the work of DownShift (on twitter somewhere), what is the benefit of creating a custom version when you still have to implement most of it yourself? Or does it actually use Downshift under the hood?

@austin94 built this perhaps he could chime in for this one.

**Comment by austin94** [comment]
:wave: Hi @Fabiantjoeaon, thanks for reaching out.

> I do have some problems with the AutoComplete example however, the examples online are a bit awkward..

You're not the first to run into this! Issue #51 points out some similar issues.

Autocompletes are traditionally (at least within our products) heavily customized for their specific use-cases. The render-prop containers for this component are very difficult to "just drop in" to a solution without customizing it heavily. The issue linked above should help address some of that awkwardness.

> I saw AutoComplete is inspired by the work of DownShift (on twitter somewhere), what is the benefit of creating a custom version when you still have to implement most of it yourself?

We try to apply a concept of [accessibility pattern separation](https://github.com/zendeskgarden/react-components/blob/master/.github/API.md) for the majority of our components, which is similar to Downshift.

The main difference is that we have this pattern for many more UI patterns: tabs, tooltips, selects, forms, tables, modals, multi-selects, etc. Since we support a larger variety of render-prop usages we have several abstractions and utilities that are specific to Garden.  These abstractions make it simpler for us to roll our own Autocomplete solution.

We are also pretty opinionated on what's the "best UX" for our end-users. There are some small tweaks/additions for user interactions with [multi-select tags](https://garden.zendesk.com/react-components/autocomplete/#!/Multi-Select/1) that differentiates us from Downshift.

**Comment by Fabiantjoeaon** [comment]
Thanks for the well explained answers @ryanseddon @austin94 , makes sense. I couldn't get the example working so I was considering writing my own Autocomplete with Downshift, but regarding all the handling of the keyboard inputs and the accessibility that comes out of the box, I changed my mind again!

However (and I was wondering if this issue could be opened again, or I could create a new one), I still can't get it working, the `MenuView` never shows up. This time I tried copying all the code from the example (including the `State` component) multiple times, but it just doesn't work. I have the feeling it has something to do with `Popper.js`, the `placement` prop returned from `AutocompleteContainer` is `undefined` for example. I tried hardcoding the value with `auto` or `bottom`, but to no avail. 

See my code below, it's literally what's displayed as example. Could you perhaps send me an example (with full code) how this works in your case?

```
import { MenuView, Item, AddItem, Separator } from "@zendeskgarden/react-menus";
import {
    TextGroup,
    Label,
    FauxInput,
    Input
} from "@zendeskgarden/react-textfields";
import { FieldContainer, KEY_CODES } from "@zendeskgarden/react-selection";
import { AutocompleteContainer } from "@zendeskgarden/react-autocomplete";
import { Component } from "react";
import PropTypes from "prop-types";
import styled from "styled-components";

class State extends Component {
    static propTypes = {
        children: PropTypes.func,
        initialState: PropTypes.object
    };

    static defaultProps = {
        initialState: {}
    };

    constructor(props) {
        super(props);
        this.state = {
            ...props.initialState
        };
    }

    render() {
        const { children, initialState } = this.props;

        return children(this.state || initialState, this.setState.bind(this));
    }
}

const NoItemsMessage = styled.div`
    margin: 16px;
    text-align: center;
`;

export default () => (
    <State
        initialState={{
            value: "Default value",
            inputValue: "",
            selectedKeys: {},
            isFocused: false,
            isOpen: false,
            focusedKey: undefined,
            natoPhonetics: [
                "Alfa",
                "Bravo",
                "Charlie",
                "Delta",
                "Echo",
                "Foxtrot",
                "Golf",
                "Hotel",
                "India",
                "Juliett",
                "Kilo",
                "Lima",
                "Mike",
                "November",
                "Oscar",
                "Papa",
                "Quebec",
                "Romeo",
                "Sierra",
                "Tango",
                "Uniform",
                "Victor",
                "Whiskey",
                "X-ray",
                "Yankee",
                "Zulu"
            ]
        }}
    >
        {(state, setState) => {
            const stringContains = (original, comparison) => {
                const formattedOriginal = original
                    .replace(/ /g, "")
                    .toLocaleLowerCase();
                const formattedComparison = comparison
                    .replace(/ /g, "")
                    .toLocaleLowerCase();

                return formattedOriginal.indexOf(formattedComparison) !== -1;
            };

            const getMatchingMenuItems = (
                searchValue,
                selectedValue,
                getItemProps,
                focusedKey
            ) => {
                const menuItems = state.natoPhonetics
                    .filter(phonetic => stringContains(phonetic, searchValue))
                    .map(phonetic => (
                        <Item
                            {...getItemProps({
                                key: phonetic,
                                focused: focusedKey === phonetic,
                                checked: selectedValue === phonetic,
                                "aria-selected": selectedValue === phonetic
                            })}
                        >
                            {phonetic}
                        </Item>
                    ));

                return menuItems.length === 0 ? (
                    <NoItemsMessage>No items found</NoItemsMessage>
                ) : (
                    menuItems
                );
            };
            return (
                <FieldContainer>
                    {({ getLabelProps, getInputProps: getFieldInputProps }) => (
                        <TextGroup>
                            <Label {...getLabelProps()}>
                                Basic Autocomplete
                            </Label>
                            <AutocompleteContainer
                                isOpen={state.isOpen}
                                focusedKey={state.focusedKey}
                                onSelect={selectedKey => {
                                    let natoPhonetics = state.natoPhonetics;

                                    if (selectedKey === "add-item") {
                                        natoPhonetics = natoPhonetics.slice();
                                        natoPhonetics.push(state.inputValue);
                                        selectedKey = state.inputValue;
                                    }

                                    setState({
                                        value: selectedKey,
                                        natoPhonetics,
                                        inputValue: ""
                                    });
                                }}
                                onStateChange={newState => {
                                    let inputValue = state.inputValue;

                                    if (
                                        typeof newState.isOpen !==
                                            "undefined" &&
                                        !newState.isOpen
                                    ) {
                                        newState.inputValue = "";
                                    }

                                    setState(newState);
                                }}
                                trigger={({
                                    getTriggerProps,
                                    getInputProps,
                                    triggerRef,
                                    inputRef,
                                    isOpen
                                }) => {
                                    return (
                                        <FauxInput
                                            {...getTriggerProps({
                                                open: isOpen,
                                                focused:
                                                    state.isFocused || isOpen,
                                                select: true,
                                                inputRef: ref => {
                                                    this.wrapperRef = ref;
                                                    triggerRef(ref);
                                                }
                                            })}
                                        >
                                            {!isOpen && (
                                                <span>{state.value}</span>
                                            )}
                                            <Input
                                                {...getInputProps(
                                                    getFieldInputProps(
                                                        {
                                                            bare: true,
                                                            innerRef: inputRef,
                                                            value:
                                                                state.inputValue,
                                                            onChange: e => {
                                                                setState({
                                                                    inputValue:
                                                                        e.target
                                                                            .value
                                                                });
                                                            },
                                                            placeholder:
                                                                state.value,
                                                            onFocus: () => {
                                                                setState({
                                                                    isFocused: true
                                                                });
                                                            },
                                                            onBlur: () => {
                                                                setState({
                                                                    isFocused: false
                                                                });
                                                            },
                                                            onKeyDown: e => {
                                                                if (
                                                                    e.keyCode ===
                                                                        KEY_CODES.ENTER &&
                                                                    (!e.target
                                                                        .value ||
                                                                        e.target.value.trim()
                                                                            .length ===
                                                                            0) &&
                                                                    !state.focusedKey &&
                                                                    state.isOpen
                                                                ) {
                                                                    e.preventDefault();
                                                                }
                                                            },
                                                            style: !isOpen
                                                                ? {
                                                                      opacity: 0,
                                                                      height: 0,
                                                                      minHeight: 0,
                                                                      width: 0,
                                                                      minWidth: 0
                                                                  }
                                                                : {}
                                                        },
                                                        { isDescribed: false }
                                                    )
                                                )}
                                            />
                                        </FauxInput>
                                    );
                                }}
                            >
                                {({
                                    getMenuProps,
                                    getItemProps,
                                    placement,
                                    focusedKey
                                }) => {
                                    const menuItems = getMatchingMenuItems(
                                        state.inputValue,
                                        state.value,
                                        getItemProps,
                                        focusedKey
                                    );
                                    console.log(placement);

                                    const addItemProps =
                                        state.inputValue.length === 0
                                            ? { disabled: true }
                                            : getItemProps({
                                                  key: "add-item",
                                                  focused:
                                                      focusedKey === "add-item"
                                              });

                                    return (
                                        <MenuView
                                            {...getMenuProps({
                                                placement,
                                                animate: true,
                                                style: {
                                                    width: `${200}px`
                                                }
                                            })}
                                        >
                                            <div
                                                style={{
                                                    height: "200px",
                                                    overflowY: "auto"
                                                }}
                                            >
                                                {menuItems}
                                            </div>
                                            <Separator />
                                            <AddItem {...addItemProps}>
                                                Add item
                                            </AddItem>
                                        </MenuView>
                                    );
                                }}
                            </AutocompleteContainer>
                        </TextGroup>
                    )}
                </FieldContainer>
            );
        }}
    </State>
);
```

**Comment by Fabiantjoeaon** [comment]
Note; I am using SSR with Next.js, and I also get this error in the console:

`index.js:2178 Warning: Prop `id` did not match. Server: "garden-field-container-82--label" Client: "garden-field-container-0--label"`, but I doubt it has something to do with it.

**Comment by austin94** [comment]
@Fabiantjoeaon I'll spin up a Codepen example of the autocomplete this morning and post here.

> Note; I am using SSR with Next.js, and I also get this error in the console:

That is a different issue, but still important. It looks like there is a missmatch with the ID global provided by `@zendeskgarden/react-selection`.  Could you take a look at our [nextjs example](https://github.com/zendeskgarden/react-components/tree/master/examples/nextjs) and see if the configurations are similar? Specifically the global ID reset in [_document.js](https://github.com/zendeskgarden/react-components/blob/master/examples/nextjs/pages/_document.js#L22)

**Comment by Fabiantjoeaon** [comment]
Awesome, @austin94, thanks a lot. And yep, didn't see the usage of the ID manager, fixes the problem.

**Comment by austin94** [comment]
Here is a working example in Codesandbox https://codesandbox.io/s/o3mp89n66 

The autocomplete logic can be found under `src/components/AutocompleteExample.js`

Once we have a chance to create a more custom documentation site for our needs we should have some better examples that are more copy-pastable 😬Let me know if you have any questions.

**Comment by Fabiantjoeaon** [comment]
Thanks for the example! I still can't get it working locally with the same code however.. I do receive the following warning from `styled-components`:

`The "innerRef" API has been removed in styled-components v4 in favor of React 16 ref forwarding, use "ref" instead like a typical component.`

I believe I saw in the source that the ref supplied from popper.js is passed to MenuWrapper, might it have something to do with using `innerRef` still under the hood?

**Comment by austin94** [comment]
All of our components are still locked to `styled-components@^3.X`. You should see some `peerDependency` warnings when you run a `yarn/npm install`

If you downgrade your `styled-components` package to `v3.4.9` it should correct that issue.

**Comment by Fabiantjoeaon** [comment]
Thanks @austin94 , it's working now, though I had to change `innerRef: inputRef`  to 
```
innerRef: ref => {
    inputRef(ref);
},
```

for `.focus()` to work.

I was making use of some of the newer `styled-components` API features, I cloned and checked into the codebase of this repo against the `styled-components` changelog, I'm willing to make a PR to update to V4, if it's not too difficult (perhaps only the change of `innerRef` > `ref`)? Or is it way more complicated?

**Comment by austin94** [comment]
Changing it to `ref` will fix the usages within the example, but there are some internal usages (specifically for the popper.js placements) that will continue to fail.

>  I'm willing to make a PR to update to V4, if it's not too difficult (perhaps only the change of innerRef > ref)

We currently have a Renovate PR started for this in #192 

Unfortunately, v4 changes the minimum `react` and `react-dom` version to `^16.3.0`. So even though it's a relatively easy change on our end it has some wider impacts to our consumers (which several are still on React v15 ☹️)

The current goal is to have it all upgraded by the end of this month

**Comment by ryanseddon** [comment]
> However (and I was wondering if this issue could be opened again, or I could create a new one),

My bad I assumed the creator of the issue could re-open it if needed, looks like @austin94 got you sorted feel free to file any other issues if you find them.
