### ISSUE TITLE
TextField fails with conditionally rendered children

### ISSUE THREAD

**Issue by Fabiantjoeaon** [zendeskgarden/react-components#218]
## Expectations
I expected TextField to conditonally render children, with the possibility to also render null if nothing is returned (from a ternary for example):

```
  <InputWrapper>
            <TextField disabled={disabled}>
                <Label htmlFor={name}>{label}</Label>
                {hint !== null && <Hint>{hint}</Hint>}
                <ZendeskInput
                    name={name}
                    validation={validationState}
                    {...props}
                />
                // Could render null:
                {validationState === "error" && (
                    <Message validation={"error"}>MES</Message>
                )}
                {message !== null && <Message>{message}</Message>}
            </TextField>
        </InputWrapper>
```

## Reality
This throws an error:
`Unhandled Rejection (TypeError): Cannot read property 'type' of null`

I now use a current workaround by rendering a empty element when `false`.

## Steps to Reproduce
Passing `null` as child to `TextField` causes this error

###### Fine Print

* Component: TextField
* Browsers: Chrome

**Comment by Fabiantjoeaon** [comment]
Linked to [https://github.com/zendeskgarden/react-components/issues/50](url) but then for `TextField`

**Comment by ryanseddon** [comment]
@Fabiantjoeaon `<TextField>` always expects children can I ask what your use-case is for not rendering children? 

If you can create a codesandbox with your code this will help us great;ly.

**Comment by ryanseddon** [comment]
ooff yeah that shouldn't happen, this is an easy fix will put something up for review soon.

**Comment by ryanseddon** [comment]
@Fabiantjoeaon this is fixed now if you bump `@zendeskgarden/react-textfields` to the latest `3.6.0` it'll fix your issue see updated test case https://codesandbox.io/s/rml24n3xrn
