### ISSUE TITLE
Add `isLoading` property to `Autocomplete` and `MutliSelect` components

### ISSUE THREAD

**Issue by austin94** [zendeskgarden/react-components#239]
## Expectations

Using our `<Dots />` loader is a common use-case within our filterable components, Autocomplete and MultiSelect.

Providing an opinionated placement for the loading/async state would be helpful for consumers. 

Original feature request by @sunesimonsen 

###### Fine Print

* Component: `@zendeskgarden/react-autocomplete`
* Browsers: all

**Comment by vinceprofeta** [comment]
@austin94 This feature would be great!

It might also be nice to have an option to filter the data outside the component. The optionFilter is nice but with having async data it would be more efficient to handle it separately.

**Comment by austin94** [comment]
Hi @vinceprofeta. Honestly forgot we had this issue open, but your comment is timely!

We’ve started to feel the pain in our developer experience by maintaining multiple “dropdown” components in separate packages. I’m currently experimenting with a more flexible API that uses the newer Context API and Downshift. 

This newer API would allow [all the customization of Downshift](
https://github.com/downshift-js/downshift#table-of-contents) (including an ‘onInputChanged’ callback) as well as more flexibility for the type of components you provide it. So rather than having a ‘loader’ prop you should just be able to render a loader in the component.

I think we would also remove the default filter logic that we have included currently. It’s too generic to be useful.

I’m going to leave this open and post a link to the PR once it’s ready. Would love to hear your feedback on the direction.

**Comment by vinceprofeta** [comment]
@austin94 We are working on a fairly sizable project, and really enjoy working with these components. Ill definitely take a look and try it out, as well as continue posting suggestions, thoughts, questions over the next couple months!

**Comment by vinceprofeta** [comment]
@austin94 have you all made any progress here?

**Comment by austin94** [comment]
Hi @vinceprofeta, we opened a quick RFC pull-request for the newer API for some feedback last week! You can look at #299 for the example implementation

You can also demo an initial version at this Codesandbox which has some better examples

[![Edit garden-dropdown-rfc-examples](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m7rvzrxj3p?fontsize=14&module=%2Fsrc%2Fexamples%2FAdvancedMenu.js&moduleview=1)

I'm currently working on the final version this sprint and should be done soon 🤞. The only major difference from the other packages is that this will probably have react and react-dom `v16.8` as a minimum version to allow us to use hooks internally.

I'll make sure to add you to the PR once it's open!
