### ISSUE TITLE
FauxInput/MediaInput clicking area is padded, when it shouldn't be

### ISSUE THREAD

**Issue by Anifacted** [zendeskgarden/react-components#265]
## Expectations

The full area of a text field should be clickable.

## Reality

When using FauxInput with MediaInput only the area inside the padding is clickable (only the MediaInput itself).

From the Styleguide example:
![icon-field-click-bug](https://user-images.githubusercontent.com/6997051/52122396-251ed800-2623-11e9-9688-3cfd8cba9bc4.gif)

## Steps to Reproduce

  1. Go to the MediaInput example in style guide: https://garden.zendesk.com/react-components/textfields/#mediafigure
  2. Start clicking

###### Fine Print

* Component: `react-textfields`
* Browsers: all

**Comment by austin94** [comment]
When we originally created this component we wanted it to be "dumb" and only include the styling, but this is unintended.

We should be manually focusing the `MediaInput` if the outer area is clicked.

This might be worthy of a refactor (or new component) where the internal input is is just baked into the  component. The `MediaFigures` can be abstracted into it as well.

**Comment by austin94** [comment]
Short-term, this _could_ be hacked together by calling `.focus()` on the `<MediaInput />` innerRef. 

But, we need to fix it eventually.

**Comment by jzempel** [comment]
Note there's a styling bug here, too – [`.c-txt__input`](https://github.com/zendeskgarden/css-components/blob/master/packages/forms/src/_text/_base.css#L38) should have `cursor: text` added.
