### ISSUE TITLE
 Style issue while using styled-components v4

### ISSUE THREAD

**Issue by totorototo** [zendeskgarden/react-components#273]
## Expectations

I just want to display alerts or notifications. Just like is was described in documentation.
Nothing fancy, no style overriding.

## Reality

Notification style is broken. Alert style as well.

## Steps to Reproduce

  1. add styled-components dependency (v4), 
  2. create a component to display alert (using Alert or Notification),
  3. that's all

https://codesandbox.io/s/v60ryn5007

### Fine Print

* Component: Alert, Notification
* Version: latest
* Browsers: all

nb: no issue while using styled-components v3!

**Comment by ryanseddon** [comment]
Hey 👋 @totorototo thanks for the issue.

Currently we only support styled-components v3.4.10 we have plans to soon update our dependencies but codesandbox doesn't show peer dependency issues. If you were to run your example locally you'd see peerDependency version mismatch warnings in the cli.

https://github.com/zendeskgarden/react-components/blob/c6995670ea2a5d9db2107a73f5bef24f7d314a78/packages/notifications/package.json#L24-L29

I just [changed your demo](https://codesandbox.io/s/j4l4rjrwky) to use styled-components v3.4.10 and it works as expected.

You can follow #235 to see when we merge to support for styled-components v4.
