### ISSUE TITLE
Feature Request: Progress Bar

### ISSUE THREAD

**Issue by swijchers** [zendeskgarden/react-components#277]
Thanks for all the awesome components. Really speeds me up developing Zendesk apps and keep the UI in line with the Zendesk products! 

I make use of the [loader](https://garden.zendesk.com/react-components/loaders/) components, but one thing I'm missing is a progress bar. It would be nice to give the user an impression of progress, instead of only showing a waiting animation. I think you can imagine many use cases, but just to name two:
* When you need to do several (paginated) API calls.
* When you are processing a large number of records.

I think it would be cool if you could set the color ([Bootstrap example](https://getbootstrap.com/docs/4.2/components/progress/#backgrounds)) and can have an optional label ([Bootstrap example](https://getbootstrap.com/docs/4.2/components/progress/#labels)). I don't really have a use case for stacked bars and I don't really care if it's animated or not, as long as it will be as good as the other components ;)

**Comment by austin94** [comment]
Thanks for the request @swijchers! Just to keep a running tally of the necessary features of a `<Progress />` component:

* A `value` prop which provides the current progress. Possibly a value of [1-100] as a percentage?
* A `label` prop to allow users to inject a centered value within the loader
* A `color` prop to allow users to override a default color.
* Include RTL logic for label text and directionality of the animation
* Possibly add animation for the value changes of the component.

**Comment by jzempel** [comment]
Thanks @swijchers. We've added this this to our design backlog. Cheers!

**Comment by agrohs** [comment]
We have a similar need and had to resort to using the `ProgressIndicator` from the bloated @salesforce-ux/design-system (and then overrode a bunch of the styling to match the Zendesk Garden look and feel). They have 2 main components around this use case: https://react.lightningdesignsystem.com/components/progress-indicators/ (ProgressIndicator - the one we used), and https://react.lightningdesignsystem.com/components/progress-bars/ (ProgressBar)

The `ProgressIndicator` one can have 2 different display types w the same code:
![Screen Shot 2019-06-13 at 5 56 38 PM](https://user-images.githubusercontent.com/160647/60067076-d7d4fd00-96ce-11e9-9238-1bafc19df749.png)
![Screen Shot 2019-06-13 at 5 56 29 PM](https://user-images.githubusercontent.com/160647/60067082-ddcade00-96ce-11e9-8b72-897c964c0777.png)

And below is a quick screencap of what we've done with it integrated into Zendesk App and formatted to match Garden:
![Uploading Screen Shot 2019-06-24 at 10.23.33 PM.png…]()

We've also added a bunch of additional features to it around `Steps` within there self-managing their own completion status.

**Comment by jzempel** [comment]
@agrohs nice timing as we are doing design exploration on a `Stepper` component right now. Thanks for your input.

/cc @ginnywood

**Comment by agrohs** [comment]
Thanks @jzempel! More than happy to talk w/ the team at any point if helpful to look through what we have in place/what our needs are (we're certainly open to contributing anything back as well if you guys are interested). We have strong interest in removing the Salesforce component from our solution ASAP as it is quite bloated and brings in a ton of their stack that we don't use/need just for a single UI Component.

**Comment by agrohs** [comment]
Have a working, clean version of a Step Progress Bar that we rolled now using the Garden framework to eliminate any of the remnants of the SF Lightning stack from our app...happy to contribute back/review with anyone if interested?

**Comment by austin94** [comment]
@agrohs thanks for the update on your progress!

We have been looking at our internal use-cases and have found the need to separate the pattern described in this issue into a few parts.

The origin of this issue is a component that shows a continuous progress from 0 to 100%. Without individual steps.

To account for the different a11y and UX concerns that come up with the individual steps you've described we have been calling the pattern a "Stepper". I've created a new issue at #408 to track this.

I will reach out in the App Dev slack channel to get some more info on the details of your implementation to see what we can adopt when we start development.

**Comment by jzempel** [comment]
Closing as a new `Progress` component just landed. https://garden.zendesk.com/react-components/loaders/#!/Progress.

Stay tuned to #408 for Garden's progress on a `Stepper` component.
