### ISSUE TITLE
Scrollbar in Select component in Chrome

### ISSUE THREAD

**Issue by swijchers** [zendeskgarden/react-components#279]
## Expectations

I expect that the option list of the select component doesn't show a scrollbar when there's no need to scroll.

## Reality

On Google Chrome I get a scrollbar in the various selects. In Mozilla Firefox and Microsoft Edge everything is as expected.
![image](https://user-images.githubusercontent.com/20306091/53571555-82963e00-3b69-11e9-934a-16f437a1b8a8.png)
![image](https://user-images.githubusercontent.com/20306091/53571612-a48fc080-3b69-11e9-912c-997df1ed8082.png)

## Steps to Reproduce

This can be experienced at:
https://garden.zendesk.com/react-components/select/
https://codesandbox.io/s/vvz9zm8663

### Fine Print

* Component: Select
* Version: 3.5.2
* Browsers: Google Chrome (Windows, Version 72.0.3626.119 (Official Build) (64-bit))

**Comment by jzempel** [comment]
@swijchers [@zendeskgarden/react-select](https://www.npmjs.com/package/@zendeskgarden/react-select)@3.5.5 should have the fix for this.

**Comment by swijchers** [comment]
@jzempel Thanks a lot, looking great in Chrome now!
