### ISSUE TITLE
Styled components Error: object-form attrs({})

### ISSUE THREAD

**Issue by vinceprofeta** [zendeskgarden/react-components#287]
## Expectations

No warnings or errors in console.

## Reality

Styled components warning in console due to numerous react-textfields components

Functions as object-form attrs({}) keys are now deprecated and will be removed in a future version of styled-components. Switch to the new attrs(props => ({})) syntax instead for easier and more powerful composition. The attrs key in question is "className" on component "Label".

## Steps to Reproduce

  1. yarn start CRA with form element from zendesk garden
  1. check console
  1. see errors

### Fine Print

* Component: react-textfields - Label, Input, Button__StyledButton, TextGroup
* Version: 3.8.3
* Browsers: all

**Comment by austin94** [comment]
:wave: Hi @vinceprofeta. It looks like you are probably using `styled-components v^4`, we only support `v^3.2.6` at this time.  If you look at the console output from yarn you should see some peer-dependency warnings.

The v3 -> v4 migration is a large breaking change and requires us to drop support for React v14&15. We currently have a work-in-progress PR open at #235 to track this work.

Pinning the styled-components version should fix correct this issue.

**Comment by ryanseddon** [comment]
Gonna close this as solved with @austin94 comment
