### ISSUE TITLE
Zaf client with react components

### ISSUE THREAD

**Issue by ehelgueroredk** [zendeskgarden/react-components#298]
Hi, If I want to add the zaf client into this app, could you tell me how to do it?

Thanks

**Comment by austin94** [comment]
Hi @ehelgueroredk. Consuming the ZAF client falls outside the scope of these React components.  This has more to do with your projects specific Webpack configuration.

You can find some instructions for consuming the SDK in the [App Developer Guide](https://developer.zendesk.com/apps/docs/developer-guide/using_sdk).

If you continue to run into issues with consuming the SDK please create a post in the [Zendesk Apps Framework community page](https://develop.zendesk.com/hc/en-us/community/topics/360000018808).

Thanks! 👋
