### ISSUE TITLE
[Well] Code example shows funky parentheses behaviour

### ISSUE THREAD

**Issue by nchieng** [zendeskgarden/react-components#302]
I'm not sure if it is an issue, but it shows up here:
https://garden.zendesk.com/react-components/notifications/?isRtl#well

## Expectations
Parenthesis in the Well title should be preserved in RTL mode

## Reality
Parentheses show up weird in the Well Title component in RTL mode

![image](https://user-images.githubusercontent.com/29188449/55535721-b1bd4380-5703-11e9-929d-520b0b34851e.png)

## Steps to Reproduce

  1. Visit https://garden.zendesk.com/react-components/notifications/?isRtl#well

Behaviour should match screenshot.
 

### Fine Print

* Component: `Notifications.Title`
* Version: @zendeskgarden/react-notifications v3.3.3
* Browsers: Chrome Version 73.0.3683.86

**Comment by austin94** [comment]
Hi @nchieng. This is actually rendering as expected I believe.

The locale context that is provided by our `ThemeProvider` only handles whether the component should be displayed in left-to-right (LTR) or right-to-left (RTL) modes.

Along with some custom styling, it normally sets the `direction: rtl` [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/direction)

This aligns items to the right, but also changes how text is rendered. From MDN,

> the user-agent uses a complex Unicode algorithm to decide how to display the text

Normally an RTL layout would also be accompanied with text that is written/localized for RTL positioning. In our current examples we don't replace the text with an RTL applicable replacement like in real-world usage. This causes some of the punctuation to be miss-aligned.

It would be very time consuming for us to maintain translations for all of the examples in their current state. So this might be out of reach for us at this time.

**Comment by jzempel** [comment]
@austin94 while you're right that we don't want to be maintaining translations here, we can apply fixes for text that is expected to read LTR regardless of the theme direction. Like this:

`<Title><span dir="ltr">Well: Standard (Multi-line)</span></Title>`

**Comment by nchieng** [comment]
This parentheses thing has been explained here
https://labs.spotify.com/2019/04/15/right-to-left-the-mirror-world/

I don't think it is something that needs to be addressed at the component level, so will close.
