### ISSUE TITLE
Am I able to change variables?

### ISSUE THREAD

**Issue by Darksoulsong** [zendeskgarden/react-components#307]
Can I change the variables used for paddings, margins, font-weight and so on through a config file? Are these variables/properties available for configuration?

**Comment by jzempel** [comment]
@Darksoulsong at this time `react-components` builds upon CSS modules which are compiled based on fixed [css-variables](https://github.com/zendeskgarden/css-components/tree/master/packages/variables) and not exposed through [theming](https://github.com/zendeskgarden/react-components/tree/master/packages/theming) for modification.

Check out our [API](https://github.com/zendeskgarden/react-components/blob/master/.github/API.md) documentation for details on how you might use Containers with your own style configuration.

**Comment by ryanseddon** [comment]
Closing due to no further action needed.
