### ISSUE TITLE
Dropdown component performance issues

### ISSUE THREAD

**Issue by Anifacted** [zendeskgarden/react-components#321]
The new dropdown package is great!
Though, It does have a performance issue. Looks like a memory leak to me.

## Expectations

Unchanged high framerate and performance over time when hovering menus.

## Reality

![dropdown-perf](https://user-images.githubusercontent.com/6997051/57065168-ea334b80-6cc8-11e9-9186-9f387df787d9.gif)

Decreasing framerate while hovering more and more items in the same dropdown. This performance problem is "reset" when the menu is closed and reopened.

I have not run analysis in detail, but profiling in Chrome could maybe reveal the source of the problem.

## Steps to Reproduce

  1. Open a dropdown menu (E.g. the Select Usage example in the Styleguide: https://garden.zendesk.com/react-components/dropdowns/#!/Select%20usage/3)
  2. Keep hovering items until the highlighted backdrop starts lacking behind

### Fine Print

* Component: dropdowns
* Version: 0.1.1
* Browsers: Only tested in Chrome

**Comment by austin94** [comment]
It looks like this may be the offending line https://github.com/zendeskgarden/react-components/blob/master/packages/dropdowns/src/Menu/Menu.js#L68

Let me take a look at this. CC @louisscruz
