### ISSUE TITLE
Dropdown prop to always highlight selected item on open 

### ISSUE THREAD

**Issue by vinceprofeta** [zendeskgarden/react-components#322]
## Expectations
When toggling Dropdown, option for the input to be selected/highlighted or reset.

## Reality
After the first selection, opening the dropdown again the cursor is at position of cursor click without the input being highlighted to make it easier to search again

## Steps to Reproduce

  1. Open dropdown
  2. Select option
  3. Close dropdown
  4. Click option (option does not reset or is not selected)

![ss (1)](https://user-images.githubusercontent.com/1517775/57107994-22ea1980-6cf7-11e9-9fa4-062dcc351279.gif)

**Comment by ryanseddon** [comment]
Hey @vinceprofeta, good catch. I'll have a look into this.

**Comment by ryanseddon** [comment]
@vinceprofeta so you can fix this in consumer land. 

See demo: https://codesandbox.io/s/y2yn555r0x

`Dropdown` has an `onOpen` callback where you can check the `isOpen` state and in your case you can do `isOpen && setInputValue('')` assuming you're controlling the `inputValue` prop.

I also have a condition in the `renderOptions` method that checks if the `inputValue` is empty and just renders the full list of options so you don't get a flash of filtered options.

I'll leave this with @austin94 as to what our next steps will be and if we need to push a patch release.

**Comment by austin94** [comment]
Hi @vinceprofeta. Two parts to this one that I unravelled.

> When toggling Dropdown, option for the input to be selected/highlighted or reset.

Even though this is the default Downshift interaction and customizable, I think the interaction you are describing is the ideal default.  I am updating the `stateReducer` within Downshift to now reset inputValue to an empty string for many interactions. This can also be controlled by yourself with the `downshiftProps.stateReducer` options.

## Unintentional Side-effects

While playing around with this problem I also found some friction with having multiple state callbacks. With the `onHighlight`, `onOpen`, and `onInputValueChange` callbacks all being called separately it was difficult (or impossible) to safely update other stateful variables based on a state change.

i.e. Set the `inputValue` to `""` when the Dropdown is opened.

Downshift solves this with a single [onStateChange](https://github.com/downshift-js/downshift#onstatechange). I have brought this over in #326 as a breaking change. We would be interested in seeing how this change would affect your use-case.

Thanks!
