### ISSUE TITLE
Shared Context Providers

### ISSUE THREAD

**Issue by bmson** [zendeskgarden/react-components#341]
This was originally written as an [ADR](https://github.com/zendesk/zendesk_console/blob/bsmarason/ADR-019/docs/arch/adr-019.md) for Support, but might make more sense in Garden.

---

- **DateTime** handling across our product portfolio has been inconsistent, both when it comes to timeZone handling and presentation of date and time. This has become apparent when there are shared dependencies between products.

- **Localization** in external dependencies has been resolved by passing in an key/value list from each product that is retrieved from Rosetta. Another way has been to expect `window.I18N` to be available and used globally. This is fragile and locks the dependent into a state where dependencies are dependent on its consumer. Another issue has been where we store the sharable string.

## Proposal

Write external context providers that passed `local`, `translations`,
`timeZone` and `hour12` using a provider. These providers would be product agnostic and would only handle the data passthrough for externals. This would allow us to improve and unify the way we do translations and dateTime across products, same solution could be used for feature flags and other data that needs to be shared or unified between products.

###### Consumer

```javascript
import { TranslationProvider, TimestampProvider } from '@zendeskgarden/providers';
import DateTime from '@zendeskgarden/dateTime';
import Translation from '@zendeskgarden/dateTime';

<TranslationProvider locale='en-US' translations={{ … }}>
  <TimestampProvider timeZone='America/Los_Angeles' hour12={false}>

    // DateTime component
    <DateTime timestamp={…} />

    // We could fix the t function and allow it to take React element
    // string: Welcome {{name}} to {{product}}
    <Translation key='txt.shared.welcome' replace={word => {
      switch (word) {
        case 'name':    return <b>Reginald Dwight</b>
        case 'product': return <b>Support</b>
      }
    } />

  </TimestampProvider>
</TranslationProvider>
```

###### Garden Components

```javascript
// Garden providers
…
```

```javascript
// Garden dateTime component
import { TranslationContext, TimestampContext } from "@zendeskgarden/providers";

const { timeZone, hour12 } = useContext(TimestampContext);
const { locale }           = useContext(TranslationContext);

const intl = new Intl.DateTimeFormat(locale, { timeZone, hour12 });
return intl.format(timestamp);
```

```javascript
// Garden translation component
import { TranslationContext } from '@zendesk/providers';

const { key, replace } = this.props;
const { translations } = useContext(TranslationContext);

const translation = translations[key];

const matches = translation.match(/{{.*?}}/g);
const words   = translation.split(' ');  

return words.map(word => {
  matches.includes(word) && replace(word) || word;
});
```

**Comment by austin94** [comment]
Thanks @bmson for opening this issue. Since this has seemed to stay quite we're going to close this for now. 

While implementing the `Datepicker` and `DatepickerRange` components we researched global translation and localization providers. We found that many internal products and external projects do not have a consistent approach that would allow us to have this global solution.
