### ISSUE TITLE
Compatibility with react@15.3.2

### ISSUE THREAD

**Issue by luis-almeida** [zendeskgarden/react-components#37]
## Expectations

We just started trying to use zendeskgarden's react-components and we started with `react-menus`.
Since it lists `react@15` as a [peer dependency](https://github.com/zendeskgarden/react-components/blob/master/packages/menus/package.json#L33) we weren't expecting to run into compatibility issues.

## Reality

Apologies if I'm missing something obvious but here's what I'm getting when adding a `<Menu />` component in our application:
<img width="1217" alt="screen shot 2018-06-11 at 14 52 05" src="https://user-images.githubusercontent.com/1159544/41280506-66215f82-6e2f-11e8-8832-d49888b3577e.png">

## Steps to Reproduce

I've managed to reproduce the error with the basic example found in the documentation page:
https://stackblitz.com/edit/react-uadcwt
Upgrading to `react@16` fixes the issue so it seems to be related to the version of react in use.

###### Fine Print

* Component: menus
* Browsers: all

**Comment by austin94** [comment]
We have some consumers still on `v15` so I think this might be an issue specifically with Menus.

I was able to spin up a `create-react-app` with Buttons and Tabs, but the error is definitely visible if you attempt to use the Menu.

![screen shot 2018-06-12 at 9 11 10 am](https://user-images.githubusercontent.com/4030377/41302942-b23d9e26-6e20-11e8-9f4e-53ab55d4ed99.png)

I'll investigate today and update once I find anything.
