### ISSUE TITLE
Dropdown Items not receiving focus on hover in React.StrictMode

### ISSUE THREAD

**Issue by sinyang** [zendeskgarden/react-components#385]
## Expectations

When hovering over a menu item from a Dropdown Select menu, I expect that the Item should be given a hover state: having a very light blue background color.

## Reality
![NewGIF (1)](https://user-images.githubusercontent.com/6819654/60928253-b3565480-a27a-11e9-861b-0a57050632ce.gif)

When hovering over an item, the hover state on disappears/never appears on all items

## Steps to Reproduce

An example was created here:

sandbox with StrictMode set: https://codesandbox.io/s/garden-create-react-app-2o028
sandbox without StrictMode: https://codesandbox.io/s/garden-create-react-app-du5lx

### Fine Print

- Component: react-dropdowns Select and Autocomplete
- Version: 6.0.0 in sandbox, 6.2.0 locally
- Browsers: Tested in Chrome and Firefox

**Comment by austin94** [comment]
👋 Hi @sinyang. It looks like [React.StrictMode calls certain functions _twice_ to warn about side-effects](https://github.com/downshift-js/downshift/issues/403)

Many of our components in dropdowns are not idempotent as the order they're called in matters.

I think the core issue here is that dropdowns believes there are twice the number of items as expected. If you were to use keyboard nav you would see every-other key press change the focus state.

@ryanseddon how do think it would be best to address this? Maybe try and shuffle some of the logic into some `useEffect` callbacks.

**Comment by sinyang** [comment]
> I think the core issue here is that dropdowns believes there are twice the number of items as expected. If you were to use keyboard nav you would see every-other key press change the focus state.

Yep. I _did_ notice that being the case when doing a line by line debug in the transpiled Item.ts code.

If i passed in 3 items, 3 others showed up behind the scenes, but not in the UI. 

The break point I set up was hit for the following order of Items:

Item 1,
Item 1,
Item 2,
Item 2,
Item 3,
Item 3

**Comment by ryanseddon** [comment]
> how do think it would be best to address this? Maybe try and shuffle some of the logic into some useEffect callbacks.

Yeah I think we'll need to make these idempotent as StrictMode is essentially a wrapper to test future compatibility with concurrent rendering.

**Comment by austin94** [comment]
After spending a day on this I was able to get it 90% of the way there. With `StrictMode` the double-render can cause some really interesting side effects. 

[getItemProps](https://github.com/downshift-js/downshift#getitemprops) in downshift is inherently idempotent which makes any remediations here difficult. I tried several combinations of ordering and allowing this syntax:

```jsx
const items = <>
  <Item value="item-1">1</Item>
  <Item value="item-2">2</Item>
</>;

<Dropdown>
   // trigger usage
  <Menu>
    {items}
  </Menu>
</Dropdown>
```

makes it especially difficult to handle ordering. If anyone has ideas for getting this working with Downshift PRs are welcome 😄

**Comment by egiv** [comment]
Thanks @austin94 for information. I have same issue too. Removing https://learn-reactjs.ru/core/strict-mode helps me, but I don't understend how It's can help my system in the feature.

**Comment by austin94** [comment]
As this is an expected failure right now I'm going to close this. We are looking at standard `.focus()` based menu interactions (not aria-activedescendant) that could help alleviate this in the future.

[Strict mode](https://reactjs.org/docs/strict-mode.html) will require changes across multiple packages in the future so I'll create a shared issue specifically for it.
