### ISSUE TITLE
forms.input garden id does not pull in themeProvider

### ISSUE THREAD

**Issue by vinceprofeta** [zendeskgarden/react-components#425]
After upgrading to SC v4 and updating all zendesk components. forms.input is not adhering to the theme provider. I checked forms.forms.text_message and that works fine.

## Expectations
Providing 
forms.input in theme should impact garden-ids with forms.input.

## Reality
No styles are present to forms.input are made even though the garden id in the file is forms.input and the garden id in the dom is forms.input

**Comment by jzempel** [comment]
We shouldn't be listing that ID in the theming documentation. I think the component ID you are looking for is `forms.text_input`. You can locate theming IDs by observing code in the `styled` directory (https://github.com/zendeskgarden/react-components/tree/master/packages/forms/src/styled/text) and seeing what is used in conjunction with `retrieveTheme`.

**Comment by vinceprofeta** [comment]
Thanks for that! I was just looking in the Dom this whole time. Appreciate the info!
