### ISSUE TITLE
What are the available div props?

### ISSUE THREAD

**Issue by jmargolisvt** [zendeskgarden/react-components#465]
I read the documentation for several components and they say that they "accept all div props" but I am unable to find any documentation for what these div props are.  Seems like these should link to wherever that documentation might be.

**Comment by austin94** [comment]
👋 Hi @jmargolisvt. A better way of describing this would be that

> all Garden elements spread their props to the DOM

For the [Button](https://garden.zendesk.com/react-components/buttons/#button) component we have several props relating to styling: `danger, basic, muted, etc.`, but we spread all other attributes to the underlying `<button>` element.

```jsx
<Button danger onClick={...} data-test-id="any value">Hi</Button>

// would render as

<button className="styled-components-classes" onClick={..} data-test-id="any value">Hi</button>
```

By allowing this on most elements within Garden it gives the components more flexibility and keeps us from having large prop-sheets that contain events/attributes that are native to the web.

Another good example would be our [Input](https://garden.zendesk.com/react-components/forms/#input) component. Here it says `Accepts all <input /> props` which means it can receive a `value` and `onChange` handler just like a native `<input />`.

**Comment by jmargolisvt** [comment]
Thanks for the explanation.  I'm satisfied with this.  Please close this out unless it's a good reminder for a documentation update should you deem it necessary.

**Comment by austin94** [comment]
We currently have a rewrite of our documentation and website on the schedule. I'll add this issue to the queue to remind us to cover it in our architecture section!

Feel free to re-open if anything else comes up.
