### ISSUE TITLE
Modal's flexbox not updating on Chrome

### ISSUE THREAD

**Issue by QuentinBouygues** [zendeskgarden/react-components#476]
## Expectations

Hi Garden ! When updating a modal's content, modal's body height is varying but the modal is not re-centered vertically on each update:

Safari shows expected behaviour: modal re-centered at each update

## Reality

With Chrome 77 placement is not updated on every modification. I will provide videos if needed

## Steps to Reproduce

1. Open modal in Chrome 76
1. Update content height
1. See the modal is not re-centered

I tried the codeSandbox but could not get the issue: Maybe it is relative to my use of the modal in Explore, or the CodeSandbox does not mimic Chrome 77.
As I had the right behaviour on Safari I'd root for option 2.

### Fine Print

- Component: React modals
- Version: 5.5 (we did not yet switch to v6)
- Browsers: Chrome 77

**Comment by austin94** [comment]
I wasn't able to re-create this example within our documentation either

![2019-09-27 09-23-14 2019-09-27 09_24_16](https://user-images.githubusercontent.com/4030377/65785182-a8d48a00-e108-11e9-9262-2ae42de5ce07.gif)

I assume this has something to do with your environment. Could you try forcing a repaint of the modal element?

FWIW upgrading to v6 may fix this issue. I suggest you set aside some time to complete that upgrade.

**Comment by QuentinBouygues** [comment]
@austin94 Thanks for having a look, a quick update before closing: forcing a redraw did work, but the simplest fix for me was a small css override on the modal.

Plus the v6 did not fix the issue, so it is surely something to do with my environment.

For the record the css hack I added is :
```css
    top: 50%;
    transform: translateY(-50%);
```
