### ISSUE TITLE
Conditional rendering is not possible within Menus

### ISSUE THREAD

**Issue by luis-almeida** [zendeskgarden/react-components#50]
## Expectations

It should be possible to use the `&&` conditional rendering pattern within Menus.

## Reality

Rendering crashes with the following exception: 
`Uncaught TypeError: Cannot read property 'props' of null`

## Steps to Reproduce

When conditionally rendering an `Item` within `Menu` following the pattern:

```js
<Menu trigger={({ ref }) => <Button innerRef={ref}>Menu</Button>}>
  <Item key="profile">Austin Powers</Item>
  {isAdmin && <Item key="settings">Settings</Item>}
</Menu>;
```
Rendering crashes when `isAdmin` is `false`.

###### Fine Print

* Component: Menu`
* Browsers: all

**Comment by austin94** [comment]
Looks like our `Children.map` logic is too simplistic in https://github.com/zendeskgarden/react-components/blob/master/packages/menus/src/elements/Menu.js

Should be an easy fix. Will update as this gets assigned.

**Comment by eddiesholl** [comment]
I'm seeing the same type of problem in the TextField map, but in this case it fails inside the `hasType` check.

The first child here evaluates to null, not undefined, so the default param in hasType does not kick in

```
      <TextField>
        { labelText && <Label>{labelText}</Label> }
        <Textarea {...this.props}
          onChange={this.keyPressed.bind(this)} />
        <Message validation={validationLevelForTextInput}>
          {validationText}
        </Message>
      </TextField>```

**Comment by austin94** [comment]
> I'm seeing the same type of problem in the TextField map, but in this case it fails inside the hasType check.

The linked PR should resolve this issue. Should have been using the `isValidElement` check in most cases.

**Comment by eddiesholl** [comment]
In case its useful for someone, this is quite unhelpful and converts undefined to null in children
https://github.com/facebook/react/blob/aeda7b745d9c080150704feb20ea576238a1b9a1/packages/react/src/ReactChildren.js#L109
