### ISSUE TITLE
Multiselect does not accept consonants when typing Japanese in Romaji method

### ISSUE THREAD

**Issue by sunesimonsen** [zendeskgarden/react-components#598]
## Expectations

Typing Japanese in Romaji in the Multiselect should work.

## Reality 

The Multiselect component only accepts consonants when typing Japanese in Romaji.

![Jan-20-2020 09-24-33](https://user-images.githubusercontent.com/90802/72710723-fb2e3080-3b67-11ea-9ffc-6e32c847384c.gif)

## Steps to Reproduce

1. In Mac system preference, add Japanese and set the typing method to Romaji.
![inline1285255206](https://user-images.githubusercontent.com/90802/72710820-2c0e6580-3b68-11ea-93c1-a9dfa341e28a.png)
1. Choose Hiragana in Input source menu at the top right of the desktop.
![inline-198225467](https://user-images.githubusercontent.com/90802/72710846-3466a080-3b68-11ea-8bc5-a8a817d65368.png)
1. Edit an article, in Labels field type as "kakikukeko". Notice it does not accept consonants. It should have "かきくけこ".
![Jan-17-2020 16-30-39](https://user-images.githubusercontent.com/90802/72710857-392b5480-3b68-11ea-9b56-5449d73cc684.gif)
1. It accepts the vowels only, the first label that is added successful below.
![Jan-17-2020 16-14-26](https://user-images.githubusercontent.com/90802/72710880-42b4bc80-3b68-11ea-9fa8-7cb66f809e01.gif)

### Fine Print

- Component: dropdowns
- Version: 7.1.5
- Browsers: all

**Comment by sunesimonsen** [comment]
## Workaround

Using the `onInputValueChange` prop for updating the input instead of `onStateChange` fixes the problem, see https://garden.zendesk.com/react-components/dropdowns/#!/Dropdown

**Comment by austin94** [comment]
This is a side-effect of IME issues within Downshift. The `onInputValueChange` prop should work correctly for us, but there also seems to be an open PR in Downshift with a fix we may want to try https://github.com/downshift-js/downshift/pull/671

**Comment by silviuaavram** [comment]
I would like to jump-start that fix again in downshift. Do you have more context around it? Do we get 2 change events with these languages? One with `isComposing` true one with false? How does it work or can you provide some documentation? Thanks!

**Comment by austin94** [comment]
It's been a while, but I believe you are correct. There was one with `isComposing` and another after the `compositionend` lifecycle.

I believe a fix an `event.which === 229` check was also necessary for some platforms (IE11 especially).

**Comment by silviuaavram** [comment]
Great, thanks! Can you confirm the fix in Downshift's Pr and review it as well please?

**Comment by jzempel** [comment]
Closing as this appears to have been addressed.
