### ISSUE TITLE
This project has been added to the react-ui-roundup

### ISSUE THREAD

**Issue by dimitropoulos** [zendeskgarden/react-components#656]
Hi!

I am making this issue just to let you know that I've included your amazing project in the [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup).

For more information see https://github.com/dimitropoulos/react-ui-roundup/issues/2.

Please feel free to close this issue at will - I just wanted to let you know :smile:.

Thanks!

**Comment by austin94** [comment]
Thanks for the update! Closing for now.

**Comment by jzempel** [comment]
Nice project, @dimitropoulos – we're honored to be included. btw, all Garden components are fully RTL ready (there's a toggle in the sidebar on all demo pages) and we do have "Switch" component (named Toggle): https://garden.zendesk.com/react-components/forms/#toggle. Cheers.

**Comment by dimitropoulos** [comment]
ahhhh! great! I hadn't seen that portion of the docs when I was looking for one.  thanks!

I updated here: https://github.com/dimitropoulos/react-ui-roundup/commit/41d4a04685af288868d9eaa14a50967f1451f951#diff-400195d25e8405a5ba26cfe183427fae
