### ISSUE TITLE
Autocomplete always sets <input /> to `id` when using a `{ id: 1, name: "myItem" }` approach

### ISSUE THREAD

**Issue by TimOgilvy** [zendeskgarden/react-components#660]
## Expectations

I wanted to be able to use the dropdown to select a text string, and use that for all the user interactions, but pass an Id back up.

## Reality

I can pass the Id around just fine, but the component automatically populates the id instead of the text string into the `<input />` 

## Steps to Reproduce

1. Create an autocomplete using a name/id list
![image](https://user-images.githubusercontent.com/2160666/75753618-40f13200-5d7f-11ea-89da-daf6bba03db8.png)

2. Select an item
![image](https://user-images.githubusercontent.com/2160666/75753683-5ebe9700-5d7f-11ea-8b68-eb65630e825a.png)

3. Click to type in the input.  

![image](https://user-images.githubusercontent.com/2160666/75753661-51091180-5d7f-11ea-90ff-4a45b3520de8.png)

The Id number is always injected into the input, because <Dropdown /> and <Autocomplete />  call `onInputValueChange()` with the value key, assuming that the 'value' is always the search string. It's not (in my use case at least).

**Code Sandbox Example**

https://n2lou.csb.app/
https://codesandbox.io/s/recursing-https-n2lou

### Fine Print

- Component: Autocomplete
- Version: Latest
- Browsers: Chrome tested

**Comment by austin94** [comment]
👋 Hi @TimOgilvy. We use https://github.com/downshift-js/downshift for most of this autocomplete logic. I believe if you provide a string/number `value` they will default to showing that in the input when the `isOpen` state is toggled.

I would look at their documentation for an example of customizing their [stateReducer](https://github.com/downshift-js/downshift#statereducer) to change that functionality.

Another option that we see people use is to provide an object as the `selectedItem` and use the downshift `itemToString` customization to render the label instead. I've included an example below:

https://codesandbox.io/s/wonderful-curran-g8ppu?fontsize=14&hidenavigation=1&theme=dark

**Comment by TimOgilvy** [comment]
Amazing! Thanks, I'll have a look.

Is the documentation open for PRs?  Once I've figured out my solution I'd love to be able to put it up for others to utilise.

**Comment by TimOgilvy** [comment]
Ok your example definitely solved my problem!  Let me know if I can PR this info into the docs somewhere, would be grateful for the opportunity to give something back.

**Comment by hzhu** [comment]
Marking issue as resolved 👍🏽 .

Garden's website [Select example](https://garden.zendesk.com/components/select#default) showcases using an object as the `selectedItem` and leveraging `itemToString`.
