### ISSUE TITLE
Outdated version of `polished` package , that produces problems

### ISSUE THREAD

**Issue by YuraKostin** [zendeskgarden/react-components#693]
Hello.

Thanks for the great ui kit.

I faced a problem, which [described](https://github.com/styled-components/polished/issues/491) and [fixed](https://github.com/zendeskgarden/css-components/commit/efdca3fdddaaa798fea29cbfba6e67cdc814618b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R35) by you.

Here is the packages, that also uses old `polished` package version:

- @zendeskgarden/react-loaders
- @zendeskgarden/react-breadcrumbs
- @zendeskgarden/react-buttons
- @zendeskgarden/react-forms
- @zendeskgarden/react-grid
- @zendeskgarden/react-tables
- @zendeskgarden/react-theming
- @zendeskgarden/react-typography

How can I help you? (For example provide you more information or something else)

Thanks a lot.

**Comment by austin94** [comment]
Hi @YuraKostin. The `polished` deprecation warning was added in [v3.5.0](https://github.com/styled-components/polished/releases/tag/v3.5.0), but we haven't upgraded these packages yet. Do you have a local instance defined in your `package.json`? `yarn why polished` could help here.

We normally have a sprintly [renovate bot](https://renovate.whitesourcesoftware.com/) which bumps these dependencies for us, but I'll take a deeper look this upcoming week.

**Comment by YuraKostin** [comment]
Hello.

No, I don't have polished in my package.json.

So, here is what I received from `npm-why`:
![image](https://user-images.githubusercontent.com/5627588/78500141-811c4980-775d-11ea-8d9d-41a841dd36c3.png)

I also checked my `node_modules`. There is a `polished@3.5.1` dependency:
![image](https://user-images.githubusercontent.com/5627588/78500335-7615e900-775e-11ea-9b8f-e4a7ca55d020.png)

But I'm still getting this warning messagess.

PS: the renovate bot is totally new for me, I didn't know about it, thanks =)

**Comment by YuraKostin** [comment]
I'm so sorry, guys.

These warning logs didn't produce any performance issues.

**Comment by austin94** [comment]
Let's leave this open actually. I'll take a look today and see what we can do to remove these deprecation warnings.

**Comment by YuraKostin** [comment]
Of course, it's up to you.

Thanks a lot for interaction
