### ISSUE TITLE
react-buttons Button doesn't allow change of type prop

### ISSUE THREAD

**Issue by xumi** [zendeskgarden/react-components#695]
## Expectations
I should be able to define the `type` prop of a `Button` component, to define it as `submit`, allowing my form to submit on click/enter

## Reality
After inspecting the code (https://github.com/zendeskgarden/react-components/blob/master/packages/buttons/src/styled/StyledButton.ts#L251) it appears that the code if overriding the `type` prop and setting it to `button`

## Steps to Reproduce
Sweet sweet bonus points: https://codesandbox.io/s/e6mzn

### Fine Print

- Component: react-buttons
- Version: 8.4.1
- Browsers: tested on Chrome and Firefox (OSX)

**Comment by austin94** [comment]
Good catch. I've opened #696 to correct this issue. Once merged we will deploy it in our weekly release.

Thanks for helping with the diagnosis.
