### ISSUE TITLE
Expected a string ending in "px" or a number

### ISSUE THREAD

**Issue by jmargolisvt** [zendeskgarden/react-components#732]
I am trying to upgrade to the following packages/versions:
styled-components 5.1.0 (from 3.4.9)
polished 3.6.0 (from 3.0.0)

I have updated all of my @zendeskgarden packages to the latest.  The react-buttons package is giving me this error: 

    polished.esm.js:332 Uncaught (in promise) Error: Expected a string ending in "px" or a number passed as the first argument to em(), got 6 instead.
    at polished.esm.js:637
    at sizeStyles (index.esm.js:251)
    at ../node_modules/@zendeskgarden/react-buttons/dist/index.esm.js.StyledButton.defaultProps.theme (index.esm.js:276)...

And below that:
`index.js:1 The above error occurred in the <styled.button> component: ...`

This error prevents my app from compiling.  When I comment out all of the buttons, my app loads fine.  How do I resolve this issue?

### Update
It seems the problem might be with the react-theming package?  I also upgraded that to 8.7.0.  When I comment out my ThemeProvider, the app compiles successfully.

### Fine Print

- Component: @zendeskgarden/react-buttons
- Version:  ^8.7.0
- Browsers: all

**Comment by jmargolisvt** [comment]
So, several of my issues including the one described stemmed from not having an updated DEFAULT_THEME.  I am able to compile my app by importing that, but I have no styles for my components now because this no longer works: `import '@zendeskgarden/react-buttons/dist/styles.css';`  There is no dist directory, so the styles have moved, but I'm not sure where to get them.

**Comment by austin94** [comment]
👋 Hi @jmargolisvt. Have you completed the migration steps outlined in https://github.com/zendeskgarden/react-components/blob/master/docs/migration.md ?

v8 no longer provides `styles.css` files.

**Comment by jmargolisvt** [comment]
Thank you!  This is exactly what I was looking for. :)
