### ISSUE TITLE
Trigger component adds input element

### ISSUE THREAD

**Issue by jmargolisvt** [zendeskgarden/react-components#744]
## Expectations
The Trigger should only add its children to the DOM.
```
<Dropdown onSelect={value => console.log(`Selected: ${value}`)}>
  <Trigger>
	<Button isPrimary>Add</Button>
  </Trigger>
</Dropdown>
```

## Reality
It adds an additional input element to the DOM.
```
<input aria-autocomplete="list" aria-labelledby="downshift-1-label" autocomplete="off" id="downshift-1-input" readonly="" tabindex="-1" data-garden-id="forms.input" data-garden-version="8.7.0" aria-invalid="false" class="sc-fzqNqU gdRmVt" value="">
```
I see that the example in the docs also generates this element, but it's hidden.  It seems it may be hidden by some css in https://garden.zendesk.com/css-components/utilities/index.css but I'm not using css components so I wouldn't expect to need to add this file.  What is the purpose of adding an input field to a trigger and how do I hide it without including that css file?

**Comment by austin94** [comment]
👋 Hi @jmargolisvt. This input is a side-effect of us using the [Downshift](https://github.com/downshift-js/downshift) library to provide accessibility and state management for all of the components within `react-dropdowns`. When the `Trigger` opens the menu that input is what receives focus and allows keyboard navigation.

This element is rendered via `styled-components` so no additional style-sheets should be required to change its visibility. What version of `react-dropdowns` are you using?

If you're able to reproduce the issues in 
https://codesandbox.io/s/github/zendeskgarden/react-components/tree/master/examples/codesandbox it will also help us.

**Comment by jmargolisvt** [comment]
I'm using `"@zendeskgarden/react-dropdowns": "^8.8.0"`

There are additional styles being added to the code sandbox page that start with this tag: 
`<style data-styled="active" data-styled-version="5.1.0">`

When I turn off several of those styles, the input appears.  https://imgur.com/a/iCmvALi

I'm not getting those styles, wherever it is they are coming from.

**Comment by austin94** [comment]
Those styles are injected by `styled-components`. Do you have any custom configuration for styled-components in your app? What are the versions of your other dependencies?

**Comment by jmargolisvt** [comment]
I'm not aware of any custom configurations.  I don't even know where those would be?  Which other dependencies are relevant here?  I see some style-lint related packages and `"babel-plugin-styled-components": "^1.10.7"`.

**Comment by austin94** [comment]
`babel-plugin-styled-components` is latest so that should be fine. If the implementation is working in codesandbox and failing locally my bet is on something `styled-components` related in how your app is hydrating its styles. I would take a [look through their issues](https://github.com/styled-components/styled-components/issues) to see if anyone else is experiencing a similar issue.

If you're able to reproduce it in a shareable repo let us know and we can continue looking.

**Comment by jmargolisvt** [comment]
I'm unable to find anything there.  Turns out I'm getting the styles after all.  I just hid the input and moved on.  Thanks for the help! :)
