### ISSUE TITLE
Getting react warning using Pagination component

### ISSUE THREAD

**Issue by agyant** [zendeskgarden/react-components#770]
## Observation

I am using the pagination component in my app.
```
<Pagination
        totalPages={this.state.data.totalPages}
        currentPage={this.state.currentPage || 1}
        onChange={(currentPage) => {this.setState({...this.state, ...{currentPage}}}}}
      />
```
I am getting the following warning from react: `Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.`
I also noticed that the `onChange` hook is getting called twice for a single click.
I followed the paginated table example provided here: https://garden-v7.netlify.app/tables/

### Fine Print

- Component: Pagination
- Version: "@zendeskgarden/react-pagination": "^8.12.0"
- Browsers: Tried in Chrome

Any help will be highly appreciated. Thanks!

**Comment by hzhu** [comment]
> I am getting the following warning from react: Cannot update during an existing state transition (such as within render). Render methods should be a pure function of props and state.

This issue might happen when a pagination component is used with a `class` component. It can be resolved by passing a `setState` function to React:

 ```jsx
<Pagination
  totalPages={11}
  currentPage={this.state.currentPage}
  onChange={currentPage => {
    this.setState(() => ({ currentPage })); // pass a function, not an object
  }}
/>
```

> I also noticed that the onChange hook is getting called twice for a single click.

For this issue, make sure the component isn't rendered in a [`<React.StrictMode>`](https://reactjs.org/docs/strict-mode.html) component because strict mode intentionally double-invokes state updates.
