### ISSUE TITLE
Usage of react routers

### ISSUE THREAD

**Issue by RakeshRenzous** [zendeskgarden/react-components#778]
## Expectations

I want to use anchor links in conjunction with react-routers.

## Reality

 I tried passing the Anchor element in the component property of the Link element. But it is still isn't working. Is there any work around. If i want to use this along with react-router ?

### Fine Print

- Component: 
- Version: 
- Browsers: all

**Comment by austin94** [comment]
Could you create a reproduction using our [example Codesandbox](https://codesandbox.io/s/github/zendeskgarden/react-components/tree/master/examples/codesandbox) for us to help diagnose?

Depending on your usage, you may need to wrap our `Anchor` element in another component. [Here is the example from the React Router docs.](https://reacttraining.com/react-router/web/api/Link/component-reactcomponent)

**Comment by hzhu** [comment]
Closing stale issue. Feel free to re-open with a [CodeSandbox example](https://codesandbox.io/s/github/zendeskgarden/react-components/tree/master/examples/codesandbox) of the issue in question.
