### ISSUE TITLE
Issues with opening and closing dropdowns on mobile devices

### ISSUE THREAD

**Issue by karimatthews** [zendeskgarden/react-components#813]
## Expectations

I should be able to open and close the dropdown menu using the caret on mobile devices.

## Reality

Clicking the caret to minimise the dropdown menu has no effect. Note that clicking outside the menu area successfully closes the menu. on some devices the menu will be hidden, but cannot be re-opened.

![Screen Recording 2020-07-17 at 11 25 am](https://user-images.githubusercontent.com/16496109/87738475-d8cc5580-c820-11ea-8116-6feba9d38a15.gif)

(The above recording was taken with an iphone X simulator, 13.2)

## Steps to Reproduce

1. On a mobile device (or using a simulator, e.g. saucelabs) go to https://garden.zendesk.com/react-components/dropdowns/
1. Scroll dow to `Advanced menu usage` (or any of the other dropdown examples)
1. Open the menu
1. Attempt to close the menu
1. If the menu will close, attempt to re-open it

## Testing details

Real android device
- Pixel 2XL Android v10 
- chrome and firefox
  - Menu will open but not close

Newer Real ios device 
-  iPad iOS version 13.5.1
- safari, chrome, and firefox
  - Menu will open but not close

Older Real ios device 
- Model number Mf353x/A OS version 11.4.1 (i.e. kinda old)
- safari, microsoft edge, and firefox
  - Menu is hidden when the caret is pressed, however the caret doesn't change direction, and the menu won't re-open 
 

### Fine Print

- Component: dropdowns
- Version: v8.16.0
- Browsers: mobile only

**Comment by hzhu** [comment]
I have reproduced this issue and will be looking further into it. Thanks for opening an issue for this bug @karimatthews 👍 .

**Comment by hzhu** [comment]
Looks like this might have been resolved. No longer able to reproduce this issue on the website, CodeSandbox, or Storybook. Feel free to re-open with link to reproduction of issue 👍🏽 .
