### ISSUE TITLE
Stepper not rendering properly in React.StrictMode

### ISSUE THREAD

**Issue by arondiploma** [zendeskgarden/react-components#849]
## Expectations
Stepper's label will start from 1 and increment by 1 as shown below:
 
![image](https://user-images.githubusercontent.com/5001567/91529088-40ef7a80-e93b-11ea-8964-49c25b0cc3c2.png)

## Reality
Stepper's label starts from 2 and incremented by 2.

![image](https://user-images.githubusercontent.com/5001567/91529347-b3605a80-e93b-11ea-9822-8c1cd973b45d.png)

## Steps to Reproduce

1. Create an app using Create React App
2. Install `@zendeskgarden/react-theming` and `@zendeskgarden/react-accordions`
3. Use the example of `Stepper` from https://zendeskgarden.github.io/react-components/accordions/ 

## Example 
https://codesandbox.io/s/zendesk-garden-stepper-w5ujw

**Comment by hzhu** [comment]
@arondiploma thanks for opening this issue and putting it on the radar. We don't have a timeline for a fix at this time but hope to address it before the next major release of Garden and/or React. This issue can be kept open until a solution is proposed.

**Comment by austin94** [comment]
I believe this is related to https://github.com/zendeskgarden/react-components/issues/385

Even though we're not using downshift here, we're still incrementing indexes based on render order. In `StrictMode` render is called twice which is messing with our logic.

**Comment by arondiploma** [comment]
> @arondiploma thanks for opening this issue and putting it on the radar. We don't have a timeline for a fix at this time but hope to address it before the next major release of Garden and/or React. This issue can be kept open until a solution is proposed.

I think this is related to some issues in other components in `StrictMode` but I want to open this issue so that the team is aware of it.

**Comment by arondiploma** [comment]
> I believe this is related to #385
> 
> Even though we're not using downshift here, we're still incrementing indexes based on render order. In `StrictMode` render is called twice which is messing with our logic.

My initial assessment is related to that issue

**Comment by jzempel** [comment]
@hzhu have a look at `CodeBlock`'s CSS-only solution to a similar problem: https://github.com/zendeskgarden/react-components/blob/d3918bfeca6a7c446e72152f13eeb6598ac8d2d9/packages/typography/src/styled/StyledCodeBlockLine.ts#L14-L28

Seems like a similar approach could be used here.

**Comment by MarkSFrancis** [comment]
@hzhu Are you open to PRs for this?

**Comment by hzhu** [comment]
Hey @MarkSFrancis, pull requests are welcomed on the project.
