### ISSUE TITLE
Tabs Component React Warning: bad setState() call inside `ForwardRef`

### ISSUE THREAD

**Issue by kurdin** [zendeskgarden/react-components#891]
## Expectations
Tabs component onChange method returns new selected tab with no warning

## Reality

Tabs component onChange method React throw Warning: 

```
Cannot update a component (`XXX`) while rendering a different component (`ForwardRef`). To locate the bad setState() call inside `ForwardRef`, follow the stack trace as described in https://fb.me/setstate-in-render
    in ForwardRef (created by XXX)
```

![image](https://user-images.githubusercontent.com/6027060/94996679-11541380-0574-11eb-9ea3-807361cdf7d2.png)

## Steps to Reproduce

https://codesandbox.io/s/ht72y?module=src/Example.tsx

### Fine Print

- Component: Tabs
- Version: 8.24.0
- Browsers: all

**Comment by hzhu** [comment]
Hi @kurdin :wave:. Thanks for creating a GitHub and CodeSandbox for this problem. I'm going to take a look and come back with updates shortly.
