### ISSUE TITLE
Browser support list for v8

### ISSUE THREAD

**Issue by Rezrazi** [zendeskgarden/react-components#899]
Hey,
Is there a browser support list for the current build ? 
And I would like to know if the browser support is unifie: across all packages.

**Comment by hzhu** [comment]
Hi @Rezrazi, the browser support is unified across all packages in this repository. For each pull request, browser testing is done across these browsers: Chrome, Firefox, Safari, Internet Explorer Edge, and Internet Explorer 11. These browsers are listed in the pull request template checklist and can be found [here](https://github.com/zendeskgarden/react-components/blob/main/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by Rezrazi** [comment]
Are polyfills shipped by default or need to be added separately ?
I'm trying to use some components in a IE11 friendly environment, but the app fails to render correctly.

```javascript
import React from "react";
import { ThemeProvider } from "@zendeskgarden/react-theming";
import { Button } from "@zendeskgarden/react-buttons";

function App() {
  return (
    <ThemeProvider>
      <>
        <Button onClick={() => alert("clicked")}>Default</Button>
        <Button isPrimary isDanger>
          Primary danger button
        </Button>
      </>
    </ThemeProvider>
  );
}

export default App;
```

```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ]
  }
```

this snippet works on modern browsers, but fails to render the component on IE11

**Comment by Rezrazi** [comment]
@austingreendev Yes, visiting the docs site from IE11 does work and all components are rendered correctly.

I have setup a sample project with CRA to which I added Garden. The problem persists and the components do not get rendered under IE11
https://github.com/Rezrazi/garden_ie11

**Comment by austingreendev** [comment]
We are only able to build the Garden assets with IE11 in mind. Depending on how your application is scaffolded you may need polyfills for the non-Garden code.

If you're using create-react-app I believe they [don't support IE11 out of the box](https://create-react-app.dev/docs/supported-browsers-features/) (with or without Garden). Using `react-app-polyfill` seems to be the standard approach for solving this.

**Comment by Rezrazi** [comment]
Thank you for your answer, it was indeed a create-react-app limitation and IE11 compatibility needed to be included manually.
