### ISSUE TITLE
Question: versioning react-components vs. react-containers

### ISSUE THREAD

**Issue by tk-o** [zendeskgarden/react-components#901]
Hello folks! 

This may be a silly question, but why have you decided to use single-version approach for `react-components` ([lerna config](https://github.com/zendeskgarden/react-components/blob/main/lerna.json#L2)), while `react-containers` project has independent versioning ([lerna config](https://github.com/zendeskgarden/react-containers/blob/main/lerna.json#L3))?

I'd appreciate if you could share some more context behind picking the versioning style in each case.

Thank you!

**Comment by jzempel** [comment]
Hi @tk-o,

Original lerna configs used independent versioning for both `react-components` and `react-containers`. But there was some community pain around the question of "which components work well together?". Since v6 of `react-components`, we locked package versions in order to address that question.

There doesn't seem to be the same confusion of the `react-containers` side. We've considered the notion of locking those versions, but right now independent versioning is serving us well, allowing some convenient version stamping flexibility across the hooks which don't have a visual connection to each other.

That's our perspective. How is the mismatch affecting you? We'd like to take any feedback you might have into consideration.

Cheers.

**Comment by austingreendev** [comment]
For us the choice came down to the types of assets that each project provides. Previous to `v6` react-components was actually [released with independent versioning](https://github.com/zendeskgarden/react-components/tags?after=v6.0.0)!

## react-containers

The packages within `react-containers` are implemented in a way that allows them to consumed and upgraded individually. They have [relatively few peer dependencies](https://github.com/zendeskgarden/react-containers/blob/main/packages/accordion/package.json#L27-L31) and are lightweight enough to be duplicated across versions without significant bundle-size increases.

i.e. If a consumer is on  `v1` of `container-accordions` and `v3` of `container-selection` they can be upgraded individually.

## react-components

The packages within `react-components` are more complex than the containers. They [require more peer dependencies](https://github.com/zendeskgarden/react-components/blob/main/packages/dropdowns/package.json#L32-L38) and can potentially have complex inter-dependency ranges between packages. When we were doing individual versioning with unique majors the interdependencies could be difficult to compare between packages.

i.e. If a consumer is on `v4` of `react-tabs` and `v3` of `react-forms` they both need to upgrade from `v4->v5` of `react-theming` to upgrade.

Moving to a single, shared major is easier to communicate. i.e. "Migrate everything to v8".

**Comment by tk-o** [comment]
Thank you @jzempel and @austingreendev for quick responses. I don't have any issue with @zendesk-garden, I'm designing a design system for my company, and simply love the way you folks solved lots of problems 🤘 There are divided opinions in terms of versioning strategy, so I was looking for more insights on the practical applications to understand the problem better.

**Comment by tk-o** [comment]
One more question on architecture, if I may. What made you to split into two repositories (one for components, one for containers)?

**Comment by jzempel** [comment]
Although `react-components` builds upon `react-containers`, we felt that the two concepts were conceptually distinct and deserved their own dedicated space – documentation, PR checklists, corresponding npm prefix, etc.

**Comment by tk-o** [comment]
Thank you so much for this clarification! Once again, you did, folks, great work here with the Garden 🚀
