### ISSUE TITLE
Double scrollbars on Modal when overflowing with Checkbox

### ISSUE THREAD

**Issue by toddoglethorpe** [zendeskgarden/react-components#938]
The picture says it all but if there's a `<Checkbox />` component in the body of a modal and the body content does overflow, a second (obviously unwanted) scrollbar is present.

## Reality
![modal](https://user-images.githubusercontent.com/48776034/99414387-9c326880-28ab-11eb-94af-50397e0c9819.png)

## Steps to Reproduce

https://codesandbox.io/s/boring-sea-btsuf?file=/src/App.js

### Fine Print

- Component: modal, form 
- Version: 8.26.0
- Browsers: Chrome 86.0.4240.198 on Fedora

**Comment by jzempel** [comment]
@toddoglethorpe thanks for the clear, concise issue and sandbox. I'm looking into a fix for this one.
