### ISSUE TITLE
Alerts not mobile friendly

### ISSUE THREAD

**Issue by joshmedeski** [zendeskgarden/react-components#949]
## Expectations
I was hoping alerts would be friendly on smaller screens.

## Reality
Alerts are not mobile-friendly, they overflow the screen and are not optimized for smaller screens.

## Steps to Reproduce

1. Create an alert
2. View the output on a screen (less than 550px wide)

### Fine Print

- Component: `<Modal>`
- Version: `8.25.2`
- Browsers: all

### Notes

I will be manually overwriting the CSS so I can deliver the product I'm building to my customer. If I create a decent solution I can spend some time later and integrate it into the repo and make a pull request.

**Comment by hzhu** [comment]
Hi @joshmedeski, `Alert` components do not have an explicit width and should work on mobile screens. Here's an example of `Alert` usage on a mobile device from https://garden.zendesk.com/components/alerts:

<img width="435" alt="Screen Shot 2021-04-02 at 2 32 50 PM" src="https://user-images.githubusercontent.com/1811365/113455762-52f93600-93c0-11eb-8e1c-933f750f9579.png">

I'm going to close this issue. Feel free to re-open with a CodeSandbox demo if you believe there is a bug. Thanks!

**Comment by joshmedeski** [comment]
Sorry @hzhu, I meant to say the `<Modal>` component is not mobile-friendly. I've updated the description and here is a screenshot.

![Screen Shot 2021-04-06 at 9 53 03 AM](https://user-images.githubusercontent.com/2036594/113731136-22feab00-96be-11eb-8bf0-05ce1cacf889.png)

**Comment by jzempel** [comment]
Yes, this is a known issue in our backlog that we have yet to prioritize for design.

**Comment by PavlMais** [comment]
It's still not fixed
