### ISSUE TITLE
Typings are broken with the latest release (8.30.0)

### ISSUE THREAD

**Issue by apkoponen** [zendeskgarden/react-components#996]
## Expectations

Typings are included in the folder, which "types" in package.json points to.

## Reality

Typings are no present, where they should be. Instead of `index.d.ts`, there is a folder matching the package name in the folder. E.g. for `@zendeskgarden/react-typography` there is a folder called `typography`.

## Steps to Reproduce

* Run `yarn init` to start a new project
* Run `yarn add @zendeskgarden/react-typography`
* Run `ls node_modules/@zendeskgarden/react-typography/dist/typings`
* See that instead of `index.d.ts` there is just a folder called `typography`

Here's a comparison between 8.28.1 and 8.30.0 versions of zendeskgarden libraries:
![Screenshot 2021-01-26 at 12 41 10](https://user-images.githubusercontent.com/5046650/105835181-272e8e00-5fd4-11eb-9296-7c77b6c2283e.png)

**Comment by austingreendev** [comment]
Hi @apkoponen. Thanks for the detailed issue description. I believe we have identified the issue and will be posting a PR shortly.

**Comment by austingreendev** [comment]
This issue is resolved in #997. We will release this during our scheduled release tomorrow. Thanks for the help!

**Comment by apkoponen** [comment]
Thanks for the quick response! 👏
